### ISSUE TITLE
Re-order settings in package.json alphabetically

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-isort#103]
Having the settings in alphabetical order makes it easier to scan through the list when looking for a setting.

**Comment by TheAfroOfDoom** [comment]
can this task be assigned to me?

**Comment by luabud** [comment]
Hi @TheAfroOfDoom! Thanks for your interested in contributing to our repo 🥳

We're participating on [Grace Hopper's Open Source Day](https://ghc.anitab.org/programs-and-awards/open-source-day/) this year, happening on September 16th, and we created a lot of "good first issues" across several of our Python extensions repos for first time contributors who are participating on the event that day. If no one shows interest in tackling this issue until the end of the event, we would love to have your contribution in case you're still up for it! 

I'm tagging issues that we were hoping to take to Open Source Day with the "ghc-osd" tag to mark them as "reserved" until the day of the event. When it's over, we'll remove the tags from issues like this 😊

**Comment by MarissaMunilall** [comment]
@luabud Can I please be assigned to this issue?

**Comment by kate-kee** [comment]
@luabud can you assign this to me as part of Grace Hopper's Open Source Day?

**Comment by luabud** [comment]
Sorry folks! I assigned it to @MarissaMunilall as she commented first

**Comment by luabud** [comment]
Just to make it clearer, this is about sorting the whole blocks under the properties field, based on the strings after "isort.":

![image](https://user-images.githubusercontent.com/45497113/190697893-cf5b95c3-e7c3-4e41-b9be-047c9179a623.png)

No need to sort the items between those blocks 😊
