### ISSUE TITLE
Add support for yapf formatter

### ISSUE THREAD

**Issue by Spenhouet** [microsoft/vscode-isort#111]
The example config in the README shows `"isort.args": ["--profile", "black"]` but we are using yapf as formatter.
I tried setting "yapf" here but then isort throws this error:

> isort.exceptions.ProfileDoesNotExist: Specified profile of yapf does not exist. Available profiles: black,django,pycharm,google,open_stack,plone,attrs,hug,wemake,appnexus.

From this I take it that yapf is not yet supported.
I hope this can be added.

**Comment by karthiknadig** [comment]
The extension is a wrapper around `isort` pyhton library. When you pass those `isort.args` they are beeing passed to the `isort` tool. think `python -m isort --profile yapf`. So, you should be filing this as a feature request on `isort` here https://github.com/pycqa/isort

**Comment by karthiknadig** [comment]
Looks like there is `google` can you try with that for profile:
```
--profile PROFILE     Base profile type to use for configuration. Profiles include: black, django, pycharm, google, open_stack,  
                        plone, attrs, hug, wemake, appnexus. As well as any shared profiles.
```

**Comment by Spenhouet** [comment]
Thanks for the hint. I just saw that myself and also found this thread arguing about if this is actually correct: https://github.com/PyCQA/isort/issues/1486
It does format imports differently to how we are used to from yapf but I can't say if it's incorrect or not.

I will raise further issues on that with isort if necessary.
