### ISSUE TITLE
"Sort imports" has no effect

### ISSUE THREAD

**Issue by s-banach** [microsoft/vscode-isort#139]
The imports are not sorted in any way.

I'm using the latest version of VSCode and python extensions on Windows 11.
I have tried with two environments, python 3.9.13 and 3.10.6, freshly installed from conda forge.
I have tried `Python Refactor: Sort imports` from the command palette.
I have tried adding the following settings to settings.json:
```
    "[python]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        },
      },
      "isort.args":["--profile", "black"],
```

(The black formatter works properly.)
I'm not sure what else I can try.

**Comment by karthiknadig** [comment]
`isort` does not contribute `Python Refactor: Sort Imports`. If you have the isort extension then use the `Organize Imports` command.

**Comment by karthiknadig** [comment]
Also, if `Organize Imports` is not working, please share the output from Output > isort panel.
![image](https://user-images.githubusercontent.com/3840081/200033709-09059088-3784-4312-b0af-0cdc5f7d83e9.png)

**Comment by s-banach** [comment]
I don't seem to have an `Organize Imports` command.  
<img width="454" alt="no_such_command" src="https://user-images.githubusercontent.com/45150804/200087802-940550b5-3408-482c-a75a-534deaa4da7f.png">

When I save a document, which is supposed to trigger `Organize Imports`, nothing appears in Output > isort.

**Comment by karthiknadig** [comment]
@s-banach Can you share hat is the version of the python extension, isort extension and vscode you have?

You should be able to see this command, which is exposed by VS Code itself for most languages.
![image](https://user-images.githubusercontent.com/3840081/200088130-1794cb8e-8ca7-4715-93dd-d9c01fcfa78c.png)

**Comment by s-banach** [comment]
VS Code Version: 1.73.0 (user setup)
ms-python.python: v2022.18.1
ms-python.sort: v2022.4.0

**Comment by karthiknadig** [comment]
Can you share the logs from both Output>isort and Output > python?

**Comment by s-banach** [comment]
Output > python on open:
```
LSP Notebooks experiment is enabled
LSP Notebooks interactive window support is enabled
> conda info --json
Python interpreter path: ~\miniforge3\python.exe
> conda run -n base --no-capture-output python ~\.vscode\extensions\ms-python.python-2022.18.1\pythonFiles\get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.18.1/pythonFiles/printEnvVariables.py
> ~\miniforge3\python.exe ~\.vscode\extensions\ms-python.python-2022.18.1\pythonFiles\get_output_via_markers.py ~\.vscode\extensions\ms-python.python-2022.18.1\pythonFiles\interpreterInfo.py
Starting Pylance language server.
```

Output > python on save:
```
> conda run -n base --no-capture-output python ~\.vscode\extensions\ms-python.python-2022.18.1\pythonFiles\get_output_via_markers.py -m black --diff --quiet ~\Documents\python\plot_results.py
cwd: ~\.vscode\extensions\ms-python.python-2022.18.1\out\client
```

Output > isort is completely blank.

**Comment by karthiknadig** [comment]
What is the version of python you have? also, can you Help > toggle developer tools. See if there are any errors reported?

**Comment by karthiknadig** [comment]
Also, can you check the "runtime status" from the extension view:
Go to extensions view:
![image](https://user-images.githubusercontent.com/3840081/200089536-64434a0f-3096-47cf-8479-02dbf6eb522d.png)

Clicking on `isort` extensions should show the content below:
![image](https://user-images.githubusercontent.com/3840081/200089498-d979fd30-57c2-417a-967f-b5132b2eae37.png)

**Comment by s-banach** [comment]
I'm using python 3.10.6 (which is the base environment for miniconda forge).

The other python extensions show their activation time, but isort just says "Not yet activated":

<img width="496" alt="not_yet_activated" src="https://user-images.githubusercontent.com/45150804/200096033-6748ab71-9de4-4c09-a49b-c40e6cd2dec3.png">

**Comment by geozeke** [comment]
This is interesting. I'm having the exact same issue, but just on Ubuntu (22.04). On vscode on a Mac (Ventura - 13.0), it works fine. I can see the "Organize Imports" option in the command pallet, and everything works as expected. On Ubuntu 22.04 I'm having the same experience as @s-banach.

Running Python 3.10.6 on both machines.

vscode in Ubuntu: 

```shell
Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:44:09.336Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-52-generic
Sandboxed: No
```

vscode on the Mac:

```shell
Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:38:50.881Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.1.0
Sandboxed: No
```

**Comment by karthiknadig** [comment]
I am suspecting that the `ms-python.isort` is shome how corrupted. I recommend trying this:
1. uninstall `ms-python.isort` extension.
2. Close all instances of VS Code.
3. Go to `%USERPROFILE%/.vscode/extensions/` (Windows) or `~/.vscode/extensions` (linus/mac) . If using SSH/container/WSL got to `.vscode-server` instead.
4. Delete `ms-python.isort`.
5. Then Start VS Code and re-install the extension from marketplace via the extension view.

**Comment by geozeke** [comment]
Sincere thanks. Appreciate the recommendation. I tried it, but still no luck. I then spun up a fresh Ubuntu 22.04 VM, with a fresh install of vscode. The only extensions installed were those recommended by vscode for python. Still don't have the "Organize Imports" option, and still can't sort imports.

**Comment by karthiknadig** [comment]
@geozeke Sometimes when dependent packages are installed it can get corrupted. This is why i was suggesting, that you try the steps here https://github.com/microsoft/vscode-isort/issues/139#issuecomment-1304634057 specifically with isort. If specifically uninstall and re-install of `isort` extensions does not work. Then I recommend downgrading the python extension to `2022.16.*`.

**Comment by geozeke** [comment]
This is something.

If I downgrade the python extension to `2022.16.*`, everything works as expected. I can see the "Organize Imports" menu in the command palette and imports will sort properly. If I then update the python extension to the most current version again, isort no longer works.

Attached is my logfile.

[2022-11-07 17_58_04.702 [info] Extension.log](https://github.com/microsoft/vscode-isort/files/9956205/2022-11-07.17.58.04.702.info.Extension.log)

**Comment by karthiknadig** [comment]
Do you see any errors when you open developer console? (Help > Toggle Developer tools)

**Comment by geozeke** [comment]
Yes. The log is a bit of a mess (pretty extensive), but I attached it. Perhaps it will help. I've been doing some work with jupyter notebooks, so there are few errors from that I can see. The other errors relating to the ms-python extension may be informative.

[Developer Console.log](https://github.com/microsoft/vscode-isort/files/9956746/Developer.Console.log)

**Comment by karthiknadig** [comment]
@geozeke Can you share the logs form Output > Python? The logs seem to suggest that the selected interpreter is invalid, the python extension logs might have some clue (in the previous comments it looked like python was selected and running fine). The developer logs seems to suggest otherwise. Can you also try setting `isort.logLevel` to `debug`, see if that prints something in Output > isort logs?

**Comment by geozeke** [comment]
Well, it's working now and the python interpreter may have been the problem. Looking at the isort log led me to the answer, thank you for that.

I've got several projects ongoing right now, with several different virtual environments running, so it doesn't surprise me that my developer logs were full of interpreter errors. I'm constantly tearing down and building virtual environments for testing so I get those errors a lot.

When I looked at the isort log, I noticed this:

```text
Name: isort
Module: isort
Python extension loading
Waiting for interpreter from python extension.
Python extension loaded
[ERROR 2022-10-7 20:32:22.857]: Python interpreter missing:
[Option 1] Select python interpreter using the ms-python.python.
[Option 2] Set an interpreter using "isort.interpreter" setting.
```
I realized that on my Mac the system interpreter was already selected, but for some reason no interpreter was selected on my Ubuntu VM. When I added the path to the interpreter (picture below) everything started working fine. I think what may have slipped by me is the setting above `Isort:Interpreter` in the picture below. It says, *This setting may be ignored if `isort.path`is set*. I thought using the bundled version of isort defaulted to using the system interpreter. I realize now that message is referring to the `Isort:Path` setting, not the `Isort:Interpreter` setting.

No sure why rolling `ms-python` back to `2022.16.*` worked, then rolling it forward again didn't.

![image](https://user-images.githubusercontent.com/22012383/200454938-947acef1-6419-40ab-aaab-2ffc6926c389.png)

I don't remember actually choosing a default interpreter in the `Isort:Interpreter` settings on the Mac. I just thought it defaulted to `/usr/bin/python3` on a Unix-like system.

Happy it's working now though 😄. Thanks for all your help!

**Comment by geozeke** [comment]
I think I understand better what's going on.

If the interpreter path is set in the `ms-python.python` extension (first picture below) `ms-python.isort` will pick it up from there. If not, it needs to be set in the `ms-python.isort` extension. That's why it works on one machine and not another.

If you look carefully at the first picture below, you'll notice that the interpreter path setting is not synced in `ms-python.python`, but it looks like it is synced in `ms-python.isort` (second picture from my `settings.json` file. Maybe that's the reason for the inconsistent (but not incorrect) behavior.

![Annotation 2022-11-08 070548](https://user-images.githubusercontent.com/22012383/200559673-ae5cd396-e68d-4c66-983a-f4b762e25143.png)

![Annotation 2022-11-08 071357](https://user-images.githubusercontent.com/22012383/200561170-9b1413ea-08f2-460c-9683-d903f7a0dbba.png)

**Comment by karthiknadig** [comment]
Thanks @geozeke for looking into this.

Closing this issue for now, please try some of the recommendation mentioned here. If nothing works, try setting the `"isort.interpreter"` setting to a python that 3.7 or greater and it should work.
