### ISSUE TITLE
New version crash on startup

### ISSUE THREAD

**Issue by sidewinder12s** [microsoft/vscode-isort#140]
I get this error now on latest VSCode release & latest extension version:

```log
SyntaxError: future feature annotations is not defined
[Info  - 9:04:29 PM] Connection to server got closed. Server will restart.
  File "/home/gwebster/.vscode-server/extensions/ms-python.isort-2022.5.13061128/bundled/tool/server.py", line 4
    from __future__ import annotations
```

I don't think it's related to 3.11 as I'm not using that yet.

**Comment by karthiknadig** [comment]
@sidewinder12s If you are using python 3.6 or older you might get this error. Extension is supported for 3.7 or greater.

**Comment by brettcannon** [comment]
@sidewinder12s it's because you're running Python 3.6 or older:

```python
>>> import __future__
>>> __future__.annotations
_Feature((3, 7, 0, 'beta', 1), None, 16777216)
```

As @karthiknadig said, we only support Python 3.7 and newer (i.e. the [versions of Python supported upstream](https://devguide.python.org/versions/#versions)).

**Comment by sidewinder12s** [comment]
Hum, let me see if I can point this at my bazel managed version of Python. Surprised I haven't run into issues yet with other Extensions.
