### ISSUE TITLE
The isort server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by bicofevo** [microsoft/vscode-isort#147]
With every VSCode launch that error message appears:
![image](https://user-images.githubusercontent.com/99279651/200501579-4a36541c-0b8d-44d5-bb20-94c43293ac5c.png)

VSCode version details:
![image](https://user-images.githubusercontent.com/99279651/200501754-db2fae58-90f2-4946-8479-885f1f28af2c.png)

isort version - v2022.4.0

Let me know if more details needed.

**Comment by karthiknadig** [comment]
Can you share the logs from Output > isort? If you are using Python 3.6 or older it is not supported.
![image](https://user-images.githubusercontent.com/3840081/200502915-26c18c0b-d1d3-4644-b7ac-ed282e955c28.png)

**Comment by rfbr** [comment]
Hello there! 
Jumping in because I have also the same error since yesterday. 
Here are the log on my side:
```
SyntaxError: future feature annotations is not defined
[Info  - 9:03:40 AM] Connection to server got closed. Server will restart.
  File "#/.vscode-server/extensions/ms-python.isort-2022.4.0/bundled/tool/server.py", line 4
    from __future__ import annotations
```

**Comment by asommani** [comment]
Hi, I also started getting this error since yersterday! It's really annoying because my IntelliSense stop working as well.

**Comment by asommani** [comment]
I am working on a ssh server. I have also noticed that if I delete the folders `~/.vscode-server/extensions/ms-python.isort*` and `~/.vscode-server/extensions/ms-python.vscode.pylance*/`, then  my IntelliSense start working again. Now I am very confused because I thought that the IntelliSense was contained in the pylance extension.

**Comment by eleanorjboyd** [comment]
Please upgrade your python to 3.7 or newer or the other option is to uninstall the isort extension and python extension then install python extension version 2022.8.*.

**Comment by asommani** [comment]
I am using python 3.9.0 and still having the problem...

**Comment by asommani** [comment]
I don't think this issue should be closed then.

**Comment by eleanorjboyd** [comment]
Hi @asommani! Can you please file a separate issue with the logs from output > isort. Thanks!
