### ISSUE TITLE
isort crashed five times...

### ISSUE THREAD

**Issue by thistlillo** [microsoft/vscode-isort#152]
Whenever I start VSC on my Windows 10 Pro notebook and connect to a remote linux server via the `remote-ssh` extension I get the message shown in the screenshot below:

![image](https://user-images.githubusercontent.com/6717655/201038494-60cf42e6-ab54-4d6a-80ab-c95739d0434f.png)

Even if it says that it crashed five times in the last three minutes, this message is shown as soon as VSC connects to the remote server. isort is version `v2022.6.0`.

I uninstalled all the Microsoft python extensions, deleted the folders ~/.vscode-server/extensions/ms-python.*  and resintalled everything but the problem is still here.

```
Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19043
Sandboxed: No
```

**Comment by jtamyrc** [comment]
I got the same error

There is the log from isort.
```
[Info  - 6:47:31 AM] Connection to server got closed. Server will restart.
  File "/home/vscode/.vscode-server/extensions/ms-python.isort-2022.6.0/bundled/tool/server.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

**Comment by clj** [comment]
For some reason the isort server is trying to start with a Python 2 interpreter. If set the `isort.interpreter` setting to a Python 3 interpreter (e.g. `python3`) then isort works again.

I get a slightly different error in the console than the one above:
```
[Info  - 12:39:53 PM] Connection to server got closed. Server will restart.
[Error - 12:39:53 PM] Connection to server is erroring. Shutting down server.
  File "/home/vscode/.vscode/extensions/ms-python.isort-2022.6.0/bundled/tool/server.py", line 19
    def update_sys_path(path_to_add: str, strategy: str) -> None:
                                   ^
SyntaxError: invalid syntax
```

**Comment by karthiknadig** [comment]
Error on the line `from __future__ import annotations` means that you are using python version 3.6 or older. We dropped support for this in python extension with version 2022.9.* onwards. There are two options:
[Option1] If you have to work with python 3.6 or older, downgrade the python extension to 2022.8.*. Then uninstall `isort` extension.
[Option 2] Upgrade your python to 3.7 or greater.

**Comment by alanhoyle** [comment]
@karthiknadig this is quite disappointing.  I don't have a choice as to what version of Python that I have available to me on all of the servers I use and legacy code with virtualenvs might have older pythons.

**Comment by karthiknadig** [comment]
@alanhoyle with the Downgrade option you will get the `isort` support the old way. Just that it won't give you the organize imports on save feature. you will still be able to use `isort`.

**Comment by alanhoyle** [comment]
That's true today, but one presumes that you all aren't just pushing out updates with no other features...  

Yes, I get that supporting legacy versions is probably a pain....

**Comment by brettcannon** [comment]
You can specify either the path to the Python interpreter to use for executing the copy of isort we ship in the extension or the path to isort itself (that's new enough, e.g. we use the `--filename` flag which hasn't always been there). See the [settings](https://github.com/microsoft/vscode-isort#settings) on how to specify either.

**Comment by bialix** [comment]
Today VSCode auto update itself to version 1.74.1 and it starts to show me this error, right after runnig the editor. No remote session involved, although I have some extension installed. I haven't changed anything else in the system.

My default Python is 3.10.4.

I need help.

Version: 1.74.1 (system setup)
Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
Date: 2022-12-14T10:30:51.966Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 6.3.9600
Sandboxed: No

**Comment by Lexicality** [comment]
This is how I fixed it for me:
```bash
$ cd projects

$ mkdir .isorts-special-little-house

$ cd .isorts-special-little-house

$ pyenv shell 3.11.1

$ python -m venv --upgrade-deps .venv

$ source .venv/bin/activate

$ pip install --progress-bar off -q isort

$ which python
/home/lexi/projects/.isorts-special-little-house/.venv/bin/python
```
and then I set 
```json
    "isort.interpreter": [
        "/home/lexi/projects/.isorts-special-little-house/.venv/bin/python"
    ],
```
in my user settings and it's not crashed since.

It would have been nice if the extension had done things like
* Warn me that this was about to happen
* Given me a sensible error message about using the wrong version of Python
* Managed its own python env perhaps
* Fallen back to calling `isort ${filename}` in the project's environment so the menu option didn't just disappear unexpectedly
but hey, it's Microsoft.

**Comment by brettcannon** [comment]
> Where can I see error log?

You can see it in the Output panel and selecting the "isort" channel.

> ... a snarky comment made at our team's expense.

I am going to ask that people please be patient and civil about this issue. I'm sorry that your situations don't allow you to necessarily use a newer version of Python, but we have to draw a line somewhere for what Python versions we support, and so we have chosen to support Python versions that are supported upstream by the Python team. We also don't control isort, so they have their own Python support requirements which you all are bumping up against.

We do hear your suggestions and will consider how we might be able to make this easier to deal with when it happens, but also know that our team has been down by 50% since this issue was reported due to vacations, so our time has been unfortunately spent elsewhere across all of the Python extensions we maintain.

**Comment by Lexicality** [comment]
I fully respect your right not to support out of date versions of python but perhaps when you drop 3.7 in 6 months time bear in mind that your extension will be autoupdated by the 10 million people who have it installed and crashing with an import error hidden in the output panel is a really confusing way to find out that your virtual environment is no longer supported.

**Comment by alanhoyle** [comment]
I am having trouble with the extension auto-updating no matter what I do.
Perhaps there's something that I'm overlooking?

-a

--
  -  Alan Hoyle  -  ***@***.***  -  http://www.alanhoyle.com/  -

**Comment by brettcannon** [comment]
> I am having trouble with the extension auto-updating no matter what I do.

How are you selecting an older version of the extension?

**Comment by brettcannon** [comment]
> bear in mind that your extension will be autoupdated by the 10 million people who have it installed and crashing with an import error hidden in the output panel is a really confusing way to find out that your virtual environment is no longer supported.

As I said, we will be taking all of this into consideration. I expect we will be adding some UX for when people try to run the extension w/o isort installed where their version isn't supported by isort (as happened here), or if our infrastructure code has to move on beyond the Python version isort supports.

**Comment by bialix** [comment]
> This is how I fixed it for me:

I wonder if using pipx will be simpler here. So just 

```pipx install isort```

and we done.

**Comment by franneck94** [comment]
I also had this error message in WIN11, where i def. dont have any python2 installed.
After setting the "isort.interpreter": ["python"] it works again.
But how will this be different to the default behaviour?
Because its still just called "python".

**Comment by karthiknadig** [comment]
> After setting the "isort.interpreter": ["python"] it works again.

This seems like a bug in Python extension when providing the path to selected python. Please file a bug on the python extension with logs from Output > Python where you can reproduce this issue.

**Comment by karthiknadig** [comment]
This should now be fixed. It should give you details on where it is getting python form, and if it is not able to get a python it will provide details on what to do next.
