### ISSUE TITLE
Isort ignores --resolve-all-configs

### ISSUE THREAD

**Issue by CaBazaga** [microsoft/vscode-isort#158]
As title mentions it completely ignores any nested config file, in my case `setup.cfg`.

Surprisingly even when switched to environment `isort`, or even when path set to the `which isort` that actually works properly from the command line.

`isort --diff --resolve-all-configs components/core/app/gunicorn_app.py` gives completely different output as does in VScode, using the mentioned `--resolve-all-configs` arg, no matter bundled, environment or path explicit is setted up.

I've an instance of `setup.cfg` file both in project's root folder and in `components/core` folder, main difference is the `headings` strings and a `known_first_party=app` setting on the one in `components/core` folder.

This works flawlessly on command line.

**Comment by karthiknadig** [comment]
This is a bug in `isort` itself, I have filed an issue on `isort` and it has to be addressed there. 
https://github.com/PyCQA/isort/issues/1989

If you need a workaround try this:
https://github.com/microsoft/vscode-python/issues/18714#issuecomment-1100641778

**Comment by mjpieters** [comment]
Another work-around is to add `--settings-path <directory with .isort.cfg or full pathname>` to `isort.args`.
