### ISSUE TITLE
Documentation bug: isort has no '--config' command line switch.

### ISSUE THREAD

**Issue by mjpieters** [microsoft/vscode-isort#161]
The README gives this example for `isort.args`:

> Custom arguments passed to `isort`. E.g `"isort.args" = ["--config", "<file>"]`

However, `isort` doesn't have such an option. Did you perhaps mean to refences the [`--settings-path` option](https://pycqa.github.io/isort/docs/configuration/options.html#settings-path)?

**Comment by karthiknadig** [comment]
You are correct. Created a PR to fix this.
