### ISSUE TITLE
isort extension not working on remote container

### ISSUE THREAD

**Issue by markedwards** [microsoft/vscode-isort#163]
Type: <b>Bug</b>

# Behaviour
isort was working fine prior to being broken out into the new extension.  now it doesn't work at all (no sorting).
## Expected vs. Actual
I expect it to work, and it does nothing.
## Steps to reproduce:

1. Open a remote container (a docker container running on a remote server).
2. Project has [tool:isort] config in setup.cfg

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.7
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
Experiment 'pythonaacf' is active
LSP Notebooks experiment is enabled
LSP Notebooks interactive window support is enabled
Python interpreter path: /usr/local/bin/python
Starting Pylance language server.
> conda info --json
Extension search path: /home/gidev/.vscode-server/extensions
> /usr/local/bin/python ~/.vscode-server/extensions/ms-python.python-2022.20.2/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2022.20.2/pythonFiles/interpreterInfo.py
Extension search path: /home/gidev/.vscode-server/extensions
> /usr/local/bin/python ~/.vscode-server/extensions/ms-python.python-2022.20.2/pythonFiles/linter.py -m mypy --follow-imports=silent --ignore-missing-imports --show-column-numbers --no-pretty /cargo/api/public/graphql/resolve/query/post.py
cwd: /cargo/api
> /usr/local/bin/python ~/.vscode-server/extensions/ms-python.python-2022.20.2/pythonFiles/linter.py -m flake8 /cargo/api/public/graphql/resolve/query/post.py
cwd: /cargo/api
> /usr/local/bin/python ~/.vscode-server/extensions/ms-python.python-2022.20.2/pythonFiles/linter.py -m mypy --follow-imports=silent --ignore-missing-imports --show-column-numbers --no-pretty /cargo/api/public/graphql/resolve/query/post.py
cwd: /cargo/api
> /usr/local/bin/python ~/.vscode-server/extensions/ms-python.python-2022.20.2/pythonFiles/linter.py -m flake8 /cargo/api/public/graphql/resolve/query/post.py
cwd: /cargo/api
##########Linting Output - mypy##########


##########Linting Output - flake8##########


```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

linting
• flake8Enabled: true
• mypyEnabled: true

testing
• pytestEnabled: true

```

</p>
</details>

Extension version: 2022.8.0
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:22:48.959Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 4.14.262-200.489.amzn2.x86_64
Remote OS version: Linux x64 4.14.262-200.489.amzn2.x86_64
Connection to 'attached-container+7b22636f6e7461696e65724e616d65223a222f636172676f5f6f66666963655f31222c2273657474696e6773223a7b22636f6e74657874223a226d655f646576227d7d' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id 1ed310f7-1cef-41d4-acaa-253391dfe6c7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container cargo-www (cargo_www_1) @ me_dev|
|OS|Linux x64 4.14.262-200.489.amzn2.x86_64|
|CPUs|AMD EPYC 7571 (4 x 2199)|
|Memory (System)|15.52GB (6.95GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container cargo-api (cargo_backend_1) @ me_dev|
|OS|Linux x64 4.14.262-200.489.amzn2.x86_64|
|CPUs|AMD EPYC 7571 (4 x 2199)|
|Memory (System)|15.52GB (6.95GB free)|
|VM|0%|

Connection to 'attached-container+7b22636f6e7461696e65724e616d65223a222f636172676f5f6f66666963655f31222c2273657474696e6773223a7b22636f6e74657874223a226d655f646576227d7d' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
2e4cg342:30602488
gswce1:30612156
3d0df643:30608728
dbltrim-noruby:30604474
89544117:30607850

```

</details>

**Comment by ashbreeze** [comment]
Seeing the same intermittent issues after upgrading to the latest version. Sometimes it will work (takes 10+ seconds though), other times it spins for a bit and then pops up `No organize import action available`

In Extensions > isort > Runtime Status I'm seeing `write after end` errors too.

I my case, I have `skip_gitignore` turned on in `.isort.cfg`. I have noticed this to make isort run considerably slower. If I disable it in my `.isort.cfg` and then restart the extension server the isort extension seems to work reliably.

Seems like this is a combo where `skip_gitignore` makes isort take a bit, and something in the latest extension version no longer likes to wait around for it, thus the `write after end` error.

**Comment by karthiknadig** [comment]
Can you share the contents of Output > isort?

@ashbreeze  If you see issue due to specific settings in `.isort.cfg` please file it on `isort` (https://github.com/PyCQA/isort/issues).

**Comment by markedwards** [comment]
Contents of Output > isort:
```
Name: isort
Module: isort
Python extension loading
Waiting for interpreter from python extension.
Python extension loaded
```
That's it, no additional lines ever, even after saving files or running `Python Refactor: Sort Imports`

**Comment by karthiknadig** [comment]
Can you share extension host log from the output tab? 
![image](https://user-images.githubusercontent.com/3840081/202402793-1173f948-679b-4742-97d3-bcfa47e7febe.png)

Also, console logs from Help > toggle developer tools.

**Comment by markedwards** [comment]
There's nothing related to isort in Log (Extension Host), but I do see this in Log (Remote Extension Host):
```
2022-11-17 09:11:44.088 [error] Error: Header must provide a Content-Length property.
	at g.onData (/home/gidev/.vscode-server/extensions/ms-python.isort-2022.8.0/dist/extension.js:1:113959)
	at Socket.<anonymous> (/home/gidev/.vscode-server/extensions/ms-python.isort-2022.8.0/dist/extension.js:1:113680)
	at Socket.emit (node:events:526:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by ashbreeze** [comment]
@karthiknadig I don't think this is a bug on the `isort` side, more of a performance issue on their end that isn't handled well by the extension.

I filed a performance enhancement PR with them - https://github.com/PyCQA/isort/pull/2002

**Comment by markedwards** [comment]
Isn't this a communication bug between VSCode and its server?

**Comment by markedwards** [comment]
Why is this marked as "info-needed"?  What info is needed?

**Comment by markedwards** [comment]
Is there any hope of an update here?  `vscode-isort` is totally broken for my due to this.

**Comment by karthiknadig** [comment]
This seems like an issue with VS Code LSP client handling the messages. Transferring this over to the right repo.

**Comment by karthiknadig** [comment]
@markedwards Before I send send it over, can you set `isort.logLevel` to `debug` and then try and reload and see if there is any additional information. Also, can you run `pip list` from the environment that you are using on remote?

**Comment by KholdStare** [comment]
I am having the same issue. `isort` seems to be stuck. I will try pasting debug info tomorrow

**Comment by markedwards** [comment]
No additional info that I can see after setting `isort.logLevel` to debug in both my User settings and in the Remote settings.  Still just see this in Remote Extension Host output:

```
2023-01-20 10:47:22.363 [error] Error: Header must provide a Content-Length property.
	at g.onData (/home/gidev/.vscode-server/extensions/ms-python.isort-2022.8.0/dist/extension.js:1:113959)
	at Socket.<anonymous> (/home/gidev/.vscode-server/extensions/ms-python.isort-2022.8.0/dist/extension.js:1:113680)
	at Socket.emit (node:events:526:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

`pip list` output:

```
$ pip list
Package                  Version
------------------------ --------------
aiodataloader            0.3.0
aiohttp                  3.8.3
aiosignal                1.3.1
algoliasearch            2.6.2
anyio                    3.6.2
ariadne                  0.16.1
ariadne-django           0.3.0
ariadne-relay            0.1.0a8
asgiref                  3.5.2
astroid                  2.12.12
asttokens                2.1.0
async-timeout            4.0.2
attrs                    22.1.0
autopep8                 2.0.0
backcall                 0.2.0
backoff                  2.2.1
boto3                    1.26.11
botocore                 1.29.11
certifi                  2022.9.24
cffi                     1.15.1
charset-normalizer       2.1.1
coverage                 6.5.0
croniter                 1.3.8
cryptography             38.0.3
decorator                5.1.1
Django                   4.1.3
django-cors-headers      3.13.0
django-phonenumber-field 7.0.0
django-request-logging   0.7.5
django-storages          1.13.1
django-stubs             1.12.0
django-stubs-ext         0.7.0
easypost                 6.0.1
exceptiongroup           1.0.4
execnet                  1.9.0
executing                1.2.0
flake8                   5.0.4
flake8-import-order      0.18.1
frozenlist               1.3.3
google-i18n-address      2.5.2
gql                      3.4.0
graphql-core             3.2.3
graphql-relay            3.2.0
growthbook               0.3.1
gtin                     1.3.1649173518
gunicorn                 20.1.0
idna                     3.4
iniconfig                1.1.1
ipython                  8.6.0
jedi                     0.18.1
jmespath                 1.0.1
lazy-object-proxy        1.8.0
matplotlib-inline        0.1.6
mccabe                   0.7.0
multidict                6.0.2
mypy                     0.991
mypy-boto3-dynamodb      1.26.0.post1
mypy-extensions          0.4.3
packaging                21.3
parameterized            0.8.1
parso                    0.8.3
pexpect                  4.8.0
phonenumbers             8.13.0
pickleshare              0.7.5
pip                      22.3.1
pluggy                   1.0.0
prompt-toolkit           3.0.32
psutil                   5.9.4
psycopg2-binary          2.9.5
ptyprocess               0.7.0
pure-eval                0.2.2
pycodestyle              2.9.1
pycountry                22.3.5
pycparser                2.21
pydantic                 1.10.2
pyflakes                 2.5.0
Pygments                 2.13.0
PyJWT                    2.6.0
pyparsing                3.0.9
pytest                   7.2.0
pytest-cov               4.0.0
pytest-django            4.5.2
pytest-xdist             3.0.2
python-dateutil          2.8.2
pytoolconfig             1.2.2
PyYAML                   6.0
requests                 2.28.1
requests-toolbelt        0.10.1
rope                     1.4.0
s3transfer               0.6.0
setuptools               63.2.0
six                      1.16.0
sniffio                  1.3.0
sqlparse                 0.4.3
stack-data               0.6.1
starlette                0.20.4
stripe                   5.0.0
supervisor               4.2.4
tenacity                 8.1.0
tomli                    2.0.1
traitlets                5.5.0
types-croniter           1.3.2
types-pkg-resources      0.1.3
types-python-dateutil    2.8.19.4
types-pytz               2022.6.0.1
types-PyYAML             6.0.12.2
types-requests           2.28.11.5
types-urllib3            1.26.25.4
typing_extensions        4.4.0
Unidecode                1.3.6
urllib3                  1.26.12
wcwidth                  0.2.5
websockets               10.4
wheel                    0.38.4
wrapt                    1.14.1
yarl                     1.8.1
```

**Comment by markedwards** [comment]
Also, I updated the original description with Output -> Python.  Nothing mentioning isort there.

Oddly, I can't make any other isort extensions from the Marketplace work either.  Running `isort` from the command line works fine, but nothing happens on saving a file in VSCode.  Linting (flake8/mypy) works fine, just no isort.

**Comment by KholdStare** [comment]
@markedwards What version of `isort` do you have installed in the container? I am currently using `5.11.4` with the same issues

**Comment by markedwards** [comment]
I've tested with no isort installed in the container, and with `5.11.4` installed.  I don't think isort is being called at all, so its irrelevant what version is installed.

**Comment by karthiknadig** [comment]
@markedwards The error that you are seeing "Header must provide a Content-Length property." if something is writing to the stdout. This happen when some library registers pth files with `print` in them. This can also occur when a library is shadowed and that unexpected library load prints something to the output. Given that you mentioned other tools are working fine, I am suspecting some library shadowing might be occurring.

In your project do you have any python files with following names:
![image](https://user-images.githubusercontent.com/3840081/213774971-b32b9b6a-7659-4ed6-8459-02b4b30333ff.png)

**Comment by markedwards** [comment]
@karthiknadig, I do have a file called `utils.py`, but there's no `print` in it.  None of the other filenames exist.

**Comment by karthiknadig** [comment]
@markedwards do you have `importStrategy` setting set to `fromEnvironment` by chance?

**Comment by markedwards** [comment]
@karthiknadig, I do not.  All of my isort extension settings are default.

**Comment by karthiknadig** [comment]
What happens when you run this from a terminal from your project folder
```
python /home/gidev/.vscode-server/extensions/ms-python.isort-2022.8.0/bundled/tool/server.py
```
Expectation is no error is printed, and it should just wait. Keyboard interrupt (like ctrl+c) should shutdown the server.

**Comment by markedwards** [comment]
No error, server waits.  However, ctrl+c does not succeed in shutting down the server.  Second ctrl+c results in a crash:

```
$ python /home/gidev/.vscode-server/extensions/ms-python.isort-2022.8.0/bundled/tool/server.py
 [2023-01-20 18:37:39,913] [12381] [level=INFO] [pygls.feature_manager] Registered builtin feature exit
 [2023-01-20 18:37:39,914] [12381] [level=INFO] [pygls.feature_manager] Registered builtin feature initialize
 [2023-01-20 18:37:39,915] [12381] [level=INFO] [pygls.feature_manager] Registered builtin feature initialized
 [2023-01-20 18:37:39,916] [12381] [level=INFO] [pygls.feature_manager] Registered builtin feature $/setTrace
 [2023-01-20 18:37:39,916] [12381] [level=INFO] [pygls.feature_manager] Registered builtin feature shutdown
 [2023-01-20 18:37:39,917] [12381] [level=INFO] [pygls.feature_manager] Registered builtin feature textDocument/didChange
 [2023-01-20 18:37:39,918] [12381] [level=INFO] [pygls.feature_manager] Registered builtin feature textDocument/didClose
 [2023-01-20 18:37:39,919] [12381] [level=INFO] [pygls.feature_manager] Registered builtin feature textDocument/didOpen
 [2023-01-20 18:37:39,920] [12381] [level=INFO] [pygls.feature_manager] Registered builtin feature workspace/didChangeWorkspaceFolders
 [2023-01-20 18:37:39,920] [12381] [level=INFO] [pygls.feature_manager] Registered builtin feature workspace/executeCommand
 [2023-01-20 18:37:39,921] [12381] [level=INFO] [pygls.feature_manager] Registered "textDocument/didOpen" with options "None"
 [2023-01-20 18:37:39,922] [12381] [level=INFO] [pygls.feature_manager] Registered "textDocument/didSave" with options "None"
 [2023-01-20 18:37:39,929] [12381] [level=INFO] [pygls.feature_manager] Registered "textDocument/didClose" with options "None"
 [2023-01-20 18:37:39,935] [12381] [level=INFO] [pygls.feature_manager] Registered "textDocument/codeAction" with options "work_done_progress=None code_action_kinds=[<CodeActionKind.SourceOrganizeImports: 'source.organizeImports'>, <CodeActionKind.QuickFix: 'quickfix'>] resolve_provider=True"
 [2023-01-20 18:37:39,935] [12381] [level=INFO] [pygls.feature_manager] Registered "codeAction/resolve" with options "None"
 [2023-01-20 18:37:39,935] [12381] [level=INFO] [pygls.feature_manager] Registered "initialize" with options "None"
 [2023-01-20 18:37:39,936] [12381] [level=INFO] [pygls.feature_manager] Registered "exit" with options "None"
 [2023-01-20 18:37:39,937] [12381] [level=INFO] [pygls.server] Starting IO server
^C [2023-01-20 18:37:58,632] [12381] [level=INFO] [pygls.server] Shutting down the server
^CTraceback (most recent call last):
  File "/home/gidev/.vscode-server/extensions/ms-python.isort-2022.8.0/bundled/tool/server.py", line 744, in <module>
    LSP_SERVER.start_io()
  File "/home/gidev/.vscode-server/extensions/ms-python.isort-2022.8.0/bundled/libs/pygls/server.py", line 237, in start_io
    self.shutdown()
  File "/home/gidev/.vscode-server/extensions/ms-python.isort-2022.8.0/bundled/libs/pygls/server.py", line 207, in shutdown
    self._thread_pool_executor.shutdown()
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 235, in shutdown
    t.join()
  File "/usr/local/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/local/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt
Exception ignored in atexit callback: <function ProcessManager.stop_all_processes at 0x7f867dff05e0>
TypeError: ProcessManager.stop_all_processes() missing 1 required positional argument: 'self'
Fatal Python error: _enter_buffered_busy: could not acquire lock for <_io.BufferedReader name='<stdin>'> at interpreter shutdown, possibly due to daemon threads
Python runtime state: finalizing (tstate=0x000055d7e3ef47c0)

Current thread 0x00007f867ea7c740 (most recent call first):
  <no Python frame>
Aborted (core dumped)
```

**Comment by karthiknadig** [comment]
> TypeError: ProcessManager.stop_all_processes() missing 1 required positional argument: 'self'

That is a known error. That should be fixed in the next release. 

I am not sure how to dig into the header error further. @dbaeumer is there a way to log the broken message that was received by the LSP client, if yes do you know where we can find this? Particularly want to see which message got to this point:
```
2023-01-20 10:47:22.363 [error] Error: Header must provide a Content-Length property.
	at g.onData (/home/gidev/.vscode-server/extensions/ms-python.isort-2022.8.0/dist/extension.js:1:113959)
	at Socket.<anonymous> (/home/gidev/.vscode-server/extensions/ms-python.isort-2022.8.0/dist/extension.js:1:113680)
	at Socket.emit (node:events:526:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by markedwards** [comment]
This should be easily reproducible by installing the isort extension on a remote docker container.  @karthiknadig are you not able to repro?

**Comment by karthiknadig** [comment]
@markedwards Unfortunately, I have not been able to repro this. The next step for figure this out is to get the faulty message that the language server client is receiving. That should allow us to narrow down where this is occurring. 

Is it possible for you to share the container that you are using?

PS:
If you are willing to test a new build out, we have a server less mode: https://github.com/microsoft/vscode-isort/suites/10501841931/artifacts/521118312 . Download and extract the zip file, there should be a vsix. You can use `Install from vsix` command in VS Code to install this.

With that build, you should be able to set `"isort.serverEnabled": false` in your user/remote machine settings. That mode runs isort directly each time, instead of server like mode. It is less performant, but it should work better in this case.

**Comment by markedwards** [comment]
I've traced this down to customizations that my container is making to Python logging formatting.  These changes are not recent, and I'm not clear on why this would interfere with VSCode.

**Comment by markedwards** [comment]
Specifically, the customization in question is a `logging.Filter` that adds custom context to logging records.  Its this recommended Python pattern:

https://docs.python.org/3/howto/logging-cookbook.html#using-filters-to-impart-contextual-information

This is breaking something in VSCode, but I can't tell what or why.

**Comment by markedwards** [comment]
More specifically, what's happening is the custom logging filter is being added to a handler in the `root` logger, in a sitecustomize module.  I worked out a minimal repro.

/isortdemo/Dockerfile:
```
FROM python:3.10-slim-bullseye

WORKDIR /isortdemo/
COPY --chown=$USERNAME isortdemo/ /isortdemo
USER root
RUN ln -s /isortdemo/sitecustomize.py $(python -c 'import site; print(site.getsitepackages()[0])')
```

/isortdemo/sitecustomize.py:
```
import logging
import logging.config


class ContextFilter(logging.Filter):

    def filter(self, record):
        record.foo = ""
        return True


logging.config.dictConfig({
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'root_filter': {
            '()': ContextFilter,
        },
    },
    'handlers': {
        'root': {
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',
            'filters': ['root_filter'],
        },
    },
    'root': {
        'handlers': ['root'],
        'level': 'INFO',
        'propagate': False,
    },
})
```

Connect to the resulting container using VSCode, install the Python extension, and observe the issue.

**Comment by karthiknadig** [comment]
@markedwards VSCode and the isort server communicate over `stdout`. So, if something is being written to `stdout`. They communicate using JSON RPC. If something gets written to `stdout` as a part of logging customization, it will interfere.
```
'root': {
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',
            'filters': ['root_filter'],
        },
```

What happens if you configure it to write to `stderr`?
Additionally, were you able to try `"isort.serverEnabled": false` with the custom https://github.com/microsoft/vscode-isort/suites/10501841931/artifacts/521118312

**Comment by markedwards** [comment]
I haven't tried the `"isort.serverEnabled": false` yet, my guess is it will work.  But this issue goes beyond just getting isort working.  Won't this issue interfere with any VSCode communication using JSON RPC?

It shouldn't be written to stderr, this config is for logging that should go to stdout.  This is a normal python configuration on top of a standard docker container.

I think this indicates a bug of some sort on the VSCode side.  The entire customization I'm doing is in the above message, and you can easily repro.  This shouldn't break VSCode.

**Comment by karthiknadig** [comment]
@markedwards The issue is that when we run the isort server. the logging that is used the server which was previously not written to `stdout` gets written to stdout. This is what happens when I run the server with the above mentioned python config.
This breaks the communication that between VS Code and the isort server.

In the container:
![image](https://user-images.githubusercontent.com/3840081/213941392-85b61bd6-dadc-4427-b879-1e035cb2311c.png)

The expected output here upon running `server.py` is that it should be empty. Nothing should get written until VSCode sends a request to the server. And the response must be a JSON RPC message.

@brettcannon Any suggestions on what we can do to avoid this?

**Comment by markedwards** [comment]
Thanks for digging in to this @karthiknadig.  I don’t understand why simply adding a member to records in the filter would trigger unexpected output.  Without the this line there’s no issue:
```
    record.foo = “”
```

**Comment by dbaeumer** [comment]
Regarding https://github.com/microsoft/vscode-isort/issues/163#issuecomment-1398802848

The problem here is that the client receives something that doesn't contain a `Content-Length` property hence it doesn't know how long the actual message is. So the message can not be read from the stream.

This usually happens if some other part of the server for some reason writes to the stream as well and doesn't send a valid RPC message. How do you talk between client and server. If you use stdin/stdout then very likely some part of the code prints to stdout as well.

**Comment by dbaeumer** [comment]
Actually there is one other possibility: which version of the client / server are you using? Checking for the `content-length` was not case insensitive before and I fixed this for the latest 8.1.0-next release. Could this be a problem for you?

**Comment by karthiknadig** [comment]
@dbaeumer The issue was that the configuration for `logging` in python for some other package was impacting the server running in python. This was causing internal logging to leak into stdout. This was an issue on the server side.

**Comment by brettcannon** [comment]
@markedwards do you have a copy or setup of Python in your container that does **not** have your custom logging configured? You can use `isort.interpreter` to specify the command to use to run the language server for isort.

Unfortunately your global change of what Python prints out to stdout by default breaks assumptions we have about how Python will operate when we use it to run tooling. So the only way I can think of to support your container setup with this extension is for you to provide a way to have Python itself function w/o flipping on all logging for all packages.

If that doesn't work then you could set up a [task](https://code.visualstudio.com/docs/editor/tasks) in VS Code that calls isort directly and rely on it directly editing your files.

But otherwise I don't see how we can support the Python you have as-is with this extension.

**Comment by markedwards** [comment]
@brettcannon what exactly about my logging config breaks things?  The trigger in my repro above seems to be simply adding an attribute to logging record objects.  That doesn’t change anything about what’s printed to stdout.

It would be helpful to know exactly what assumptions are being made here, so I can work around the issue.

**Comment by brettcannon** [comment]
All of the following output is breaking stuff for us:
```
 [2023-01-20 18:37:39,913] [12381] [level=INFO] [pygls.feature_manager] Registered builtin feature exit
 [2023-01-20 18:37:39,914] [12381] [level=INFO] [pygls.feature_manager] Registered builtin feature initialize
 [2023-01-20 18:37:39,915] [12381] [level=INFO] [pygls.feature_manager] Registered builtin feature initialized
 [2023-01-20 18:37:39,916] [12381] [level=INFO] [pygls.feature_manager] Registered builtin feature $/setTrace
 [2023-01-20 18:37:39,916] [12381] [level=INFO] [pygls.feature_manager] Registered builtin feature shutdown
 [2023-01-20 18:37:39,917] [12381] [level=INFO] [pygls.feature_manager] Registered builtin feature textDocument/didChange
 [2023-01-20 18:37:39,918] [12381] [level=INFO] [pygls.feature_manager] Registered builtin feature textDocument/didClose
 [2023-01-20 18:37:39,919] [12381] [level=INFO] [pygls.feature_manager] Registered builtin feature textDocument/didOpen
 [2023-01-20 18:37:39,920] [12381] [level=INFO] [pygls.feature_manager] Registered builtin feature workspace/didChangeWorkspaceFolders
 [2023-01-20 18:37:39,920] [12381] [level=INFO] [pygls.feature_manager] Registered builtin feature workspace/executeCommand
 [2023-01-20 18:37:39,921] [12381] [level=INFO] [pygls.feature_manager] Registered "textDocument/didOpen" with options "None"
 [2023-01-20 18:37:39,922] [12381] [level=INFO] [pygls.feature_manager] Registered "textDocument/didSave" with options "None"
 [2023-01-20 18:37:39,929] [12381] [level=INFO] [pygls.feature_manager] Registered "textDocument/didClose" with options "None"
 [2023-01-20 18:37:39,935] [12381] [level=INFO] [pygls.feature_manager] Registered "textDocument/codeAction" with options "work_done_progress=None code_action_kinds=[<CodeActionKind.SourceOrganizeImports: 'source.organizeImports'>, <CodeActionKind.QuickFix: 'quickfix'>] resolve_provider=True"
 [2023-01-20 18:37:39,935] [12381] [level=INFO] [pygls.feature_manager] Registered "codeAction/resolve" with options "None"
 [2023-01-20 18:37:39,935] [12381] [level=INFO] [pygls.feature_manager] Registered "initialize" with options "None"
 [2023-01-20 18:37:39,936] [12381] [level=INFO] [pygls.feature_manager] Registered "exit" with options "None"
 [2023-01-20 18:37:39,937] [12381] [level=INFO] [pygls.server] Starting IO server
```

That logging from pygls is not triggered by us. My guess is the following part of your config is what's turning logging on for **all** code being run by your Python interpreter and not just your own code as well as sending all logging to stdout which breaks our communication channel to VS Code which is done via stdout:
```
 'handlers': {
        'root': {
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',
            'filters': ['root_filter'],
        },
    },
    'root': {
        'handlers': ['root'],
        'level': 'INFO',
        'propagate': False,
    },
```

Otherwise I'm not familiar enough with the logging package to provide more help.

**Comment by markedwards** [comment]
Thanks @brettcannon, this makes sense now.  Unfortunately, there are very good reasons for using this logging config, and bending it to satisfy a dev tool is kind of upside down (and might not be possible anyway).

I'll use the `isort.serverEnabled` option for now, I can confirm the custom build provided above works.

Food for thought -- maybe relying on stdout in this way is not the ideal pattern for VSCode?  I realise that is probably not something that will change, but its not uncommon for projects to have to customize stdout in order to route logs, and the project arguably shouldn't have to constrain its requirements to fit the IDE.

**Comment by brettcannon** [comment]
> maybe relying on stdout in this way is not the ideal pattern for VSCode?

It's actually a security concern for language servers, so you're right this won't be something we change. By launching language servers as subprocesses and communicating over stdin/stdout we are able to avoid security risks where we have to communicate over a local socket that runs the risk of a malicious process trying to attach (and us messing up that the right process connected).



> its not uncommon for projects to have to customize stdout in order to route logs, and the project arguably shouldn't have to constrain its requirements to fit the IDE.

This is why we let people specify a different Python install. We are unfortunately in an odd spot of not having an easy way to ship Python itself with the extension, so we have to rely on users to supply the interpreter. Hopefully some day we can maybe use WebAssembly builds of Python to run the tools, but that's a more of a long-term dream than short-term solution.

**Comment by markedwards** [comment]
👍

**Comment by coditza** [comment]
> We are unfortunately in an odd spot of not having an easy way to ship Python itself with the extension, so we have to rely on users to supply the interpreter.

Wouldn't running your thing in a venv solve this? We give you the interpreter, but you run with your own site-packages, without our customised sitepackages.py.

Using the venv module, your server script could have a bootstrap bit, that if it detects it's not running in your own venv would create it (if not existing) and use it. Looking at the activate script, shouldn't be that hard (to activate the env for your script), looks like it's just a matter of setting some env variables and switching to the interpreter in .venv (or whatever path). Will take a closer look when I get back from holiday.
