### ISSUE TITLE
Appears to leak memory

### ISSUE THREAD

**Issue by mjpieters** [microsoft/vscode-isort#165]
Type: <b>Bug</b>

I'm trying to use VSCode to edit Python code on a resource-constrained, older server (AMD Turion(tm) II Neo N40L, 6GB RAM). This has been working very well, until recently.

I've narrowed this down to the `extensions/ms-python.isort-<version>/bundled/tool/server.py` process; saving files with the current pre-release is excruciatingly slow and it has been eating up memory and using loads of CPU. Memory use starts low but as files get saved memory use creeps up and up, until the system runs out of memory and starts swapping. The preview release appears to be worse in this regard.

When I disable the extension, things become workable again.

Extension version: 2022.9.13221008
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:22:48.959Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 4.19.0-21-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 6, 8|
|Memory (System)|32.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 6ee26e67-256e-4593-8cbb-57e7fb562f53|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: parsel|
|OS|Linux x64 4.19.0-21-amd64|
|CPUs|AMD Turion(tm) II Neo N40L Dual-Core Processor (2 x 1500)|
|Memory (System)|5.70GB (0.29GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
fc301958:30595537
282f8724:30602487
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by eleanorjboyd** [comment]
Hello! I wanted to update to say we have received this issue and will be looking into it!

**Comment by karthiknadig** [comment]
can you try the pre-release? there is a server less mode as well. you can set it using `"isort.serverEnabled": false` in your user settings.

**Comment by mjpieters** [comment]
I've been running with the pre-release for a while now, and things look very stable now. Thanks for looking into this!
