### ISSUE TITLE
Warn with running with old settings from the Python extension

### ISSUE THREAD

**Issue by Avasam** [microsoft/vscode-isort#171]
isort Output from VSCode:
```
CWD Server: c:\Users\Avasam\Documents\Git\typeshed
sys.path used to run Server:
   c:\Users\Avasam\.vscode\extensions\ms-python.isort-2022.8.0\bundled\tool
   C:\Program Files\Python39\python39.zip
   C:\Program Files\Python39\DLLs
   C:\Program Files\Python39\lib
   C:\Program Files\Python39
   c:\Users\Avasam\Documents\Git\typeshed\.venv
   c:\Users\Avasam\Documents\Git\typeshed\.venv\lib\site-packages
   c:\Users\Avasam\Documents\Git\typeshed\.venv\lib\site-packages\win32
   c:\Users\Avasam\Documents\Git\typeshed\.venv\lib\site-packages\win32\lib
   c:\Users\Avasam\Documents\Git\typeshed\.venv\lib\site-packages\Pythonwin
   c:\Users\Avasam\.vscode\extensions\ms-python.isort-2022.8.0\bundled\libs
Settings used to run Server:
[
    {
        "check": true,
        "workspace": "file:///c%3A/Users/Avasam/Documents/Git/typeshed",
        "logLevel": "error",
        "args": [
            "--line-length=120",
            "--combine-as"
        ],
        "severity": {
            "W": "Warning",
            "E": "Warning"
        },
        "path": [],
        "interpreter": [
            "c:\\Users\\Avasam\\Documents\\Git\\typeshed\\.venv\\Scripts\\python.exe"
        ],
        "importStrategy": "fromEnvironment",
        "showNotifications": "off"
    }
]

c:\Users\Avasam\Documents\Git\typeshed\.venv\Scripts\python.exe -m isort --version-number
CWD Linter: c:\Users\Avasam\Documents\Git\typeshed
Version info for isort running for c:\Users\Avasam\Documents\Git\typeshed:
5.10.1

SUPPORTED isort>=5.10.1
FOUND isort==5.10.1

c:\Users\Avasam\Documents\Git\typeshed\.venv\Scripts\python.exe -m isort - --line-length=120 --combine-as --check --filename c:\Users\Avasam\Documents\Git\typeshed\stubs\python-xlib\Xlib\protocol\rq.pyi
CWD Linter: c:\Users\Avasam\Documents\Git\typeshed
ERROR: c:\Users\Avasam\Documents\Git\typeshed\stubs\python-xlib\Xlib\protocol\rq.pyi Imports are incorrectly sorted and/or formatted.
```

Settings:
![image](https://user-images.githubusercontent.com/1350584/203880258-ccfef7e0-a082-4e8e-982d-7dd886f5d0c6.png)

pyproject.toml :
```toml
[tool.isort]
profile = "black"
combine_as_imports = true
line_length = 130
```

isort in editor thinks lines are too long because they're over 120 chars. When the limit is 130:
![image](https://user-images.githubusercontent.com/1350584/203880467-49cf967a-2827-4569-9610-f6ea747f3916.png)

**Comment by brettcannon** [comment]
Is your `pyproject.toml` at the top of your workspace or in a subdirectory?

**Comment by Avasam** [comment]
It is at the top of the workspace: https://github.com/python/typeshed

**Comment by brettcannon** [comment]
I suspect there's an issue where we are reading the ruler/line wrapping setting in VS Code but not realizing there's a conflicting setting in isort (probably because it was assumed the editor would be set up to match the value in the `pyproject.toml` configuration). I assume you have 120 characters set in VS Code as the line length limit?

If that guess is right, I'm not sure what the best solution is. We don't want to be chasing isort for all of its settings, but we do know some users expect us to infer the line length from their editor settings instead of relying on isort defaults. But obviously we also have users like you who don't set the same value in VS Code as they do in their isort setting.

**Comment by Avasam** [comment]
Here's my workspace configs:

<details>
<summary>Details</summary>

{
    // Don't format on save for formatters we don't explicitely control
    "editor.formatOnSave": false,
    "editor.codeActionsOnSave": {
        "source.fixAll": false
    },
    // Set file associations to support comments
    "files.associations": {
        ".flake8": "properties",
        "stubtest_allowlist*.txt": "properties",
        "pyrightconfig*.json": "jsonc"
    },
    "files.insertFinalNewline": true,
    "editor.detectIndentation": false,
    "editor.tabSize": 2,
    "[json][jsonc][python]": {
        "editor.tabSize": 4,
    },
    "[git-commit]": {
        "editor.rulers": [
            72
        ]
    },
    "[python]": {
        "editor.defaultFormatter": "ms-python.black-formatter",
        "editor.rulers": [
            130
        ],
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.fixAll": true,
            "source.fixAll.unusedImports": true,
            "source.fixAll.convertImportFormat": true,
            "source.organizeImports": true
        },
    },
    "python.linting.enabled": true,
    "python.linting.mypyEnabled": true,
    "python.linting.mypyArgs": [
        "--show-column-numbers",
        "--no-pretty",
        "--custom-typeshed-dir=${workspaceFolder}",
        "--python-version=3.7"
    ],
    "isort.check": true,
    "isort.importStrategy": "fromEnvironment",
    // isort args have to be re-specified (https://github.com/microsoft/vscode-isort/issues/171)
    "isort.args": [
        "--profile=black",
        "--combine-as",
        "--line-length=130"
    ],
    // Not using bandit
    "python.linting.banditEnabled": false,
    // Using dedicated Flake8 extension
    "python.linting.flake8Enabled": false,
    "python.linting.pycodestyleEnabled": false,
    "python.linting.prospectorEnabled": false,
    "python.linting.pylamaEnabled": false,
    // Using the dedicated black extension
    "python.formatting.provider": "none",
    // Use the new dedicated extensions instead (and we're not using pylint)
    "python.linting.pylintEnabled": false,
}


</details>

And here's my User configs:

<details>
<summary>Details</summary>

{
  "typescript.updateImportsOnFileMove.enabled": "always",
  "editor.tabSize": 2,
  "javascript.preferences.quoteStyle": "single",
  "typescript.preferences.quoteStyle": "single",
  "python.formatting.autopep8Args": [
    "--max-line-length=120"
  ],
  "editor.rulers": [
    80,
    120
  ],
  "[git-commit]": {
    "editor.rulers": [
      72
    ]
  },
  "extensions.ignoreRecommendations": true,
  "files.insertFinalNewline": true,
  "git.confirmSync": false,
  "git.enableSmartCommit": true,
  "workbench.editorAssociations": {
    "*.ipynb": "jupyter-notebook"
  },
  "trailing-spaces.includeEmptyLines": true,
  "trailing-spaces.trimOnSave": true,
  "python.defaultInterpreterPath": "C:\\Program Files\\Python39\\python.exe",
  "trailing-spaces.syntaxIgnore": [
    "markdown"
  ],
  "notebook.cellToolbarLocation": {
    "default": "right",
    "jupyter-notebook": "left"
  },
  "workbench.iconTheme": "material-icon-theme",
  "javascript.preferences.importModuleSpecifier": "non-relative",
  "typescript.preferences.importModuleSpecifier": "non-relative",
  "javascript.updateImportsOnFileMove.enabled": "always",
  "security.workspace.trust.untrustedFiles": "open",
  "files.associations": {
    "*.qrc": "xml",
    ".coveragerc": "ini"
  },
  "python.linting.flake8Enabled": false,
  "flake8.severity": {
    "convention": "Warning",
    "error": "Error",
    "fatal": "Error",
    "refactor": "Warning",
    "warning": "Warning",
    "info": "Warning",
    // builtins
    "A": "Warning",
    // mccabe
    "C": "Warning",
    // class attributes order
    "CCE": "Warning",
    // pycodestyles
    "E": "Warning",
    "E9": "Error", // Runtime
    "W": "Warning",
    "W6": "Error", // Deprecation warning
    // Pyflakes
    "F": "Warning",
    // PEP8 Naming convention
    "N": "Warning",
    // Simplify
    "SIM": "Warning",
    "SIM9": "Information",
    // PYI
    "Y": "Warning",
  },
  "[python]": {
    "editor.defaultFormatter": "ms-python.autopep8",
    "editor.tabSize": 4,
    "editor.rulers": [
      72, // PEP8-17 docstrings
      // 79, // PEP8-17 default max
      // 88, // Black default
      99, // PEP8-17 acceptable max
      120, // Our hard rule
    ],
  },
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.fixAll": true,
    "source.fixAll.unusedImports": false,
    "source.fixAll.convertImportFormat": true,
    "source.organizeImports": true,
  },
  "python.linting.banditEnabled": true,
  "terminal.integrated.enableMultiLinePasteWarning": false,
  "explorer.confirmDelete": false,
  "powershell.codeFormatting.pipelineIndentationStyle": "IncreaseIndentationForFirstPipeline",
  "powershell.codeFormatting.autoCorrectAliases": true,
  "powershell.codeFormatting.trimWhitespaceAroundPipe": true,
  "powershell.codeFormatting.useConstantStrings": true,
  "powershell.codeFormatting.useCorrectCasing": true,
  "powershell.codeFormatting.whitespaceBetweenParameters": true,
  "powershell.integratedConsole.showOnStartup": false,
  "redhat.telemetry.enabled": true,
  "python.analysis.typeCheckingMode": "strict",
  "git.mergeEditor": false,
  "xml.codeLens.enabled": true,
  "flake8.args": [
    "--max-line-length=120"
  ],
  "python.linting.flake8Args": [
    "--max-line-length=120"
  ],
  "python.sortImports.args": [
    "--line-length=120",
    "--combine-as"
  ],
  "diffEditor.ignoreTrimWhitespace": false,
  "eslint.alwaysShowStatus": true,
  "editor.find.seedSearchStringFromSelection": "selection",
  "python.linting.mypyEnabled": true,
  "python.linting.mypyArgs": [
    "--show-column-numbers",
    "--no-pretty",
    "--custom-typeshed-dir=C:/Users/Avasam/Documents/Git/typeshed"
  ],
  "python.analysis.typeshedPaths": [
    "C:/Users/Avasam/Documents/Git/typeshed"
  ],
  "pylint.importStrategy": "fromEnvironment",
  "python.analysis.diagnosticMode": "workspace",
  "autopep8.args": [
    "--max-line-length=120"
  ],
  "workbench.experimental.settingsProfiles.enabled": true,
  "isort.check": true,
  "isort.importStrategy": "fromEnvironment",
  "isort.severity": {
    "E": "Warning"
  },
}


</details>

I found the culprit hidden in my user settings from long ago:
![image](https://user-images.githubusercontent.com/1350584/204391353-813e7cef-643c-4ccc-9b46-fa2231fb8dff.png)

I've removed the setting and I no longer see those extra arguments.

That explains why I couldn't find where those arguments came from. So technically my issue was more of a migration one (settings not found where I'd expect them). And it'll resolve itself once `python.sortImports.Args` is no longer used.

**Comment by brettcannon** [comment]
> I found the culprit hidden in my user settings from long ago

Glad it's now resolved!



> So technically my issue was more of a migration one

I've gone ahead and tweaked this issue into a feature request to warn when picking up settings from the Python extension.

**Comment by karthiknadig** [comment]
We should log when we pick up values from old settings here: https://github.com/microsoft/vscode-isort/blob/ef37d377cab60abb0a25ce983b6b6591d186aec0/src/common/settings.ts#L49
