### ISSUE TITLE
"Getting code actions" on saving a python file can hang up to 20 seconds.

### ISSUE THREAD

**Issue by willjhenry** [microsoft/vscode-isort#175]
When I save a file in python, it will show the following pop up:

"Saving ‘my_file.py': Getting code actions from ''Sourcery', 'isort'' (configure).”

This can hang for up to 20 seconds. It did not used to do this. I do not know if it is an issue with VS code, isort, or Sourcery.  Disabling isort did seem to help, but it is hard to tell because it is a little random; it does not hang every time (it does do it often enough to disrupt development).

I suppose an option is to disable running these code actions on save; however, I would prefer to run them on save.

**Comment by brettcannon** [comment]
Can you please try turning off extensions and turning them back on one by one to try and figure out which is causing the slowdown? It might also just be VS Code itself, but it's hard to tell without eliminating Sourcery from possibly being a problem.

**Comment by willjhenry** [comment]
after a few tests, I believe this is Sourcery

**Comment by brettcannon** [comment]
Thanks for letting us know in case this come up for anyone else!
