### ISSUE TITLE
isort processes left behind after VS code closes

### ISSUE THREAD

**Issue by gnought** [microsoft/vscode-isort#187]
The following isort processes don't terminate after VS code is closed.
```
41002   ??  S      0:00.63 /usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/Resources/Python.app/Contents/MacOS/Python /Users/gnought/.vscode/extensions/ms-python.isort-2022.8.0/bundled/tool/server.py
41038   ??  S      0:00.17 /usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/Resources/Python.app/Contents/MacOS/Python /Users/gnought/.vscode/extensions/ms-python.isort-2022.8.0/bundled/tool/runner.py
```
Environment: OSX, VS code 1.74.0

**Comment by orval** [comment]
similar issue for me. I killed about 30 of these processes recently. I just found another 13 running from `~/.vscode/extensions/ms-python.isort-2022.8.0/bundled/tool/server.py`

**Comment by karthiknadig** [comment]
Fixed in https://github.com/microsoft/vscode-isort/pull/207

The fix is available in pre-release. There is also a server less mode, set `"isort.serverEnabled": false` in user settings to disable server mode.
