### ISSUE TITLE
Isort server crashed 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-isort#211]
Type: <b>Bug</b>

`v2022.9.13271012`

1. Create an empty untitled file
1. Switch it's language mode to python

**bug**
See notificaiton about isort server crashing

Log:

```
Name: isort
Module: isort
Python extension loading
Waiting for interpreter from python extension.
Python extension loaded
  File "/Users/matb/.vscode-insiders/extensions/ms-python.isort-2022.9.13271012/bundled/tool/server.py", line 19
    def update_sys_path(path_to_add: str, strategy: str) -> None:
                                   ^
SyntaxError: invalid syntax
[Info  - 3:52:15 PM] Connection to server got closed. Server will restart.
  File "/Users/matb/.vscode-insiders/extensions/ms-python.isort-2022.9.13271012/bundled/tool/server.py", line 19
    def update_sys_path(path_to_add: str, strategy: str) -> None:
                                   ^
SyntaxError: invalid syntax
[Info  - 3:52:16 PM] Connection to server got closed. Server will restart.
  File "/Users/matb/.vscode-insiders/extensions/ms-python.isort-2022.9.13271012/bundled/tool/server.py", line 19
    def update_sys_path(path_to_add: str, strategy: str) -> None:
                                   ^
SyntaxError: invalid syntax
[Info  - 3:52:16 PM] Connection to server got closed. Server will restart.
  File "/Users/matb/.vscode-insiders/extensions/ms-python.isort-2022.9.13271012/bundled/tool/server.py", line 19
    def update_sys_path(path_to_add: str, strategy: str) -> None:
                                   ^
SyntaxError: invalid syntax
[Info  - 3:52:16 PM] Connection to server got closed. Server will restart.
  File "/Users/matb/.vscode-insiders/extensions/ms-python.isort-2022.9.13271012/bundled/tool/server.py", line 19
    def update_sys_path(path_to_add: str, strategy: str) -> None:
                                   ^
SyntaxError: invalid syntax
[Error - 3:52:16 PM] Connection to server got closed. Server will not be restarted.
```

Extension version: 2022.9.13271012
VS Code version: Code - Insiders 1.75.0-insider (Universal) (270c3b12906a88e9c67fc5ddef87be6aa3b75551, 2023-01-25T05:23:34.922Z)
OS version: Darwin x64 22.2.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by karthiknadig** [comment]
@mjbvz what is the python version? It seems like python 2.7 was selected.

**Comment by mjbvz** [comment]
Yes I think it got auto selected. I'm opening an issue against python for this

instead of crashing can you show an error language status, similar to what eslint does it eslint is misconfigured/crashing?

**Comment by karthiknadig** [comment]
@mjbvz Agreed. This should not run the server when the version of python is not supported.

**Comment by karthiknadig** [comment]
This should now log that the version is not supported, and skip running.
