### ISSUE TITLE
Sort Imports doesn't work with unnamed files

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode-isort#235]
Installing the pre-release version of the i-sort extension with insiders for VS Code. I have a python file but it is not saved ( I did click, python when selecting a language on a new file).  Click on `sort imports` from the right click menu. No sorting is done, then save the file with a name and now the `sort import` command works.

**Comment by karthiknadig** [comment]
`isort` requires the physical file to exist to determine how to categorize various module imported in the file. This is expected.
