### ISSUE TITLE
Imports are incorrectly sorted and/or formatted.isort(E)

### ISSUE THREAD

**Issue by Phatlynx** [microsoft/vscode-isort#237]
Error

![image](https://user-images.githubusercontent.com/67671220/217913509-a8c0319e-8d22-4ae2-b130-e73cac515a82.png)

![image](https://user-images.githubusercontent.com/67671220/217913106-eefb9d6d-1cff-4697-8b9b-80d411ea9c57.png)

If I add a space the issue is fixed, who decided import statements needs to separate?

![image](https://user-images.githubusercontent.com/67671220/217913166-5170f32a-ca1f-4897-ae59-3a1a544d5c37.png)

**Comment by karthiknadig** [comment]
This is the `isort` tool which handles import sorting. The default is to separate python standard libraries and any user libraries. This extension does not make that decision, this extension shows what is reported by `isort` in the UI.

Repo for the tool itself: https://github.com/PyCQA/isort
Settings you can use for the tool: https://pycqa.github.io/isort/docs/configuration/options.html 
The setting you are looking for is "Lines Between Sections"

**Comment by Phatlynx** [comment]
Thanks! I've disabled the extension altogether as I mainly use python for quick prototyping, therefore I don't have a need for isort. I can see where this would be useful when there's tens if not hundreds of import statements. 

It shouldn't be **On** by default though, having to learn how to config yet another extension is just cumbersome, could I suggest putting these config options inside of Settings (not the json, but the Settings UI with checkboxes)

**Comment by karthiknadig** [comment]
@Phatlynx The `check` setting is off by default:
![image](https://user-images.githubusercontent.com/3840081/217919378-9ead12b7-499b-4599-b9f4-47841ce088c7.png)

It is in the UI:
![image](https://user-images.githubusercontent.com/3840081/217919700-a922b2a6-e286-47ac-9730-1a0f741e333f.png)

Make sure that you have the latest version of the extension. As for the specific settings for `isort` the tool those are configured using whatever mechanism the tool supports.
