### ISSUE TITLE
Extension doesn't work in multi-root workspace

### ISSUE THREAD

**Issue by MattiasOlla** [microsoft/vscode-isort#244]
I have a multi-root workspace with separate virtualenvs (managed by `pyenv`), and I'm trying to organize imports on save, but I get the following error:

```
Name: isort
Module: isort
Python extension loading
Waiting for interpreter from python extension.
Python extension loaded
[ERROR 2023-1-20 13:52:52.276]: Python interpreter missing:
[Option 1] Select python interpreter using the ms-python.python.
[Option 2] Set an interpreter using "isort.interpreter" setting.
```

I definitely have a selected interpreter for each workspace folder, and I've tried with the `isort.importStrategy` as both `useBundled` and `fromEnvironment` (which would be my preference, so that the different projects can use different versions).

Python version: I've tried several, 3.11.1, 3.10.5, 3.9.7

isort plugin version: v2022.8.0 (I've also tried the pre-release version as of today, with the same result)

System info:
Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:35:30.018Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 5.19.0-32-generic snap
Sandboxed: No

**Comment by karthiknadig** [comment]
This might be an issue with python extension not returning the selected interpreter for the workspace. Can you provide logs for python (Output >Python) and your multi-root code-workspace file?.

**Comment by MattiasOlla** [comment]
In providing that input, I think I found the solution! For one of the folders in my workspace, I had changed the virtualenv set up by `pyenv` (i.e. deleted the virtualenv, created a new one with the same name but a newer python version, and reinstalled all dependencies) but NOT updated the python interpreter for that folder, so one of the pyhon interpreters didn't exist. This led to the `isort` (and `black`) extension to not work in any of the folders.

Hmmm, that might be a feature request for the Python extension, to warn if one of the selected interpreters doesn't exist anymore.

I'll still provide the input here, but I don't think it's of much use (I guess the python interpreter paths are stored somewhere else):

Output > Python:
```
Python interpreter path: ~/.pyenv/versions/3.11.1/envs/project1/bin/python
> ~/.pyenv/versions/3.11.1/envs/project1/bin/python -m black --diff --quiet ~/code/project1/dialog/forms.py
cwd: ~/code/project1
Extension search path: /home/mattias/.vscode/extensions
> ~/.pyenv/versions/3.11.1/envs/project1/bin/python ~/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/linter.py -m flake8 ~/code/project1/dialog/forms.py
cwd: ~/code/project1
> ~/.pyenv/versions/3.11.1/envs/project1/bin/python ~/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/testing_tools/run_adapter.py discover pytest -- --rootdir ~/code/project1 -s --cache-clear
cwd: ~/code/project1
##########Linting Output - flake8##########
```

`company.code-workspace`:
```jsonc
{
  "folders": [
    {
      "name": "project1",
      "path": "project1"
    },
    {
      "name": "project2",
      "path": "project2"
    },
    {
      "name": "project3",
      "path": "project3"
    }
  ],
  "settings": {
    "[python]": {
      "editor.rulers": [
        88
      ],
      "editor.wordBasedSuggestions": false,
      "gitlens.codeLens.symbolScopes": [
        "!Module"
      ]
    },
    "python.terminal.activateEnvInCurrentTerminal": false, // pyenv handles this,
    "python.terminal.activateEnvironment": false, // pyenv handles this,
  }
}

```

**Comment by karthiknadig** [comment]
This looks like it was an issue with caching in python extension. This resulted in isort getting the wrong python. You can use `Python: Clear cache and reload` command if something like this happens again.
