### ISSUE TITLE
vscode leaves isort processes running forever after exit

### ISSUE THREAD

**Issue by AddisonG** [microsoft/vscode-isort#259]
When vscode exits, several isort processes are left open, and stay open forever.

```
user  2901652  0.0  0.0 336576 31592 ?        Sl   Mar21   0:00 /usr/bin/python3 /home/user/.vscode/extensions/ms-python.isort-2022.8.0/bundled/tool/server.py
user  2901661  0.0  0.0  25804 17364 ?        S    Mar21   0:00 /home/user/.virtualenvs/my_codebase/bin/python /home/user/.vscode/extensions/ms-python.isort-2022.8.0/bundled/tool/runner.py
user  2901664  0.0  0.0  26560 17652 ?        S    Mar21   0:00 /home/user/.local/share/virtualenvs/my_venv3.8/bin/python /home/user/.vscode/extensions/ms-python.isort-2022.8.0/bundled/tool/runner.py
```

This is extremely frustrating, as if I happen to reload vscode, these processes all stack up. The exact same thing happens with the `black` formatting tool (`ms-python.black-formatter-2022.6.0`).

I think this may partly be a problem with this code, under `main/bundled/tool/lsp_jsonrpc.py`:

```
class ProcessManager:

    def stop_all_processes(self):   <-----
        ...
```

I don't know for sure, but I think the `stop_all_processes()` call is not meant to take a parameter (`self`).

I can reproduce this 100% of the time, and it has been happening for about 6 or 12 months. I cannot seem to find anyone else out there who has the problem though.

Example stack trace, when running this manually, then attempting to kill it:

```
Traceback (most recent call last):
  File "/home/user/.vscode/extensions/ms-python.black-formatter-2022.6.0/bundled/tool/runner.py", line 43, in <module>
    msg = RPC.receive_data()
  File "/home/user/.vscode/extensions/ms-python.black-formatter-2022.6.0/bundled/tool/jsonrpc.py", line 117, in receive_data
    return self._reader.read()
  File "/home/user/.vscode/extensions/ms-python.black-formatter-2022.6.0/bundled/tool/jsonrpc.py", line 75, in read
    line = to_str(self._readline())
  File "/home/user/.vscode/extensions/ms-python.black-formatter-2022.6.0/bundled/tool/jsonrpc.py", line 87, in _readline
    line = self._reader.readline()
KeyboardInterrupt
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
```

**Comment by karthiknadig** [comment]
@AddisonG This should be fixed in main. Can you try the pre-release version of the extension?

PS: We are waiting on a fix from `isort` library to be released, and then we can publish a new release.

**Comment by AddisonG** [comment]
Thanks, that does seem to fix it. Excellent work - Sorry for raising a bug when it's already on the way.

Thanks for maintaining this.

**Comment by SchoolGuy** [comment]
Would it be possible to release a new version that includes this fix? I have three servers running at the same time that eat memory and CPU.

**Comment by karthiknadig** [comment]
This is now released in stable.
