### ISSUE TITLE
Isort fails with "ERROR: Filename override is intended only for stream (-) sorting."

### ISSUE THREAD

**Issue by ldorigo** [microsoft/vscode-isort#263]
Type: <b>Bug</b>

/bin/python -m isort - --profile black --filename /data/Dropbox/foo/bar/react_dashboard/backend/app/endpoints/banner.py
CWD Linter: /data/Dropbox/foo/bar/react_dashboard/backend
ERROR: Filename override is intended only for stream (-) sorting.

Relevant config lines:

```json
  "isort.check": true,
  "isort.showNotifications": "onError",
  "editor.inlineSuggest.showToolbar": "always",
  "isort.importStrategy": "fromEnvironment",
  "isort.args": ["--profile black"],
```

Extension version: 2023.9.10931010
VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:57:21.103Z)
OS version: Linux x64 6.2.9-zen1-1-zen
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics (16 x 4284)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|30.77GB (10.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by karthiknadig** [comment]
@ldorigo Can you provide logs from Output > isort? Also, was the file empty when this happened?

**Comment by ldorigo** [comment]
Hi, no the file was not empty. The output contains the 3 lines I pasted above repeated everytime I save or manually run "sort imports". I can paste the startup outputs when I get home .

**Comment by karthiknadig** [comment]
@ldorigo I need to see the initial part of the logs where it lists out sys.path, isort version etc.

**Comment by geoff-va** [comment]
This error seems to go away when you set
```
  "isort.args": ["--profile", "black"],
```

as separate entries.

But unless I'm misunderstanding some of these settings, it doesn't seem to be respecting the black profile when I use it as separate args.

Example:

isort settings
```
    "isort.args": [
        "--profile",
        "black"
    ],
```
Then
```
from some_package import (X, Y,)

# gets sorted to

from some_package import X, Y
```

This does not produce the filename error.

If I use a single arg for the isort args:
```
    "isort.args": [
        "--profile black"
    ],
```
Then
```
from some_package import (X, Y,)

# gets sorted to

from some_package import (
    X,
    Y,
)
```

Which is the behavior I would expect from the black profile, but now i get the filename Error ?

**Comment by geoff-va** [comment]
Hey @karthiknadig 

This was the sample script:
```python
from urllib import (parse, request, )
```

Which gets formatted to:
```python
from urllib import parse, request
```

While (at least based on my understanding of the `--profile black` option) should result in:
```python
from urllib import (
    parse, 
    request
)
```

Here is the output of `Output -> isort`:

```text
sys.path used to run Server:
   /<home-dir>/.vscode/extensions/ms-python.isort-2023.9.10931010/bundled/libs
   /<home-dir>/.vscode/extensions/ms-python.isort-2023.9.10931010/bundled/tool
   /<home-dir>/.pyenv/versions/3.10.5/envs/<project>/lib/python3.10/site-packages/_pdbpp_path_hack
   /<home-dir>/.pyenv/versions/3.10.5/lib/python310.zip
   /<home-dir>/.pyenv/versions/3.10.5/lib/python3.10
   /<home-dir>/.pyenv/versions/3.10.5/lib/python3.10/lib-dynload
   /<home-dir>/.pyenv/versions/3.10.5/envs/<project>/lib/python3.10/site-packages
Settings used to run Server:
[
    {
        "check": false,
        "cwd": "<path-to-project-workspace>",
        "workspace": "file://<path-to-project-workspace>",
        "logLevel": "error",
        "args": [
            "--profile",
            "black"
        ],
        "severity": {
            "W": "Warning",
            "E": "Hint"
        },
        "path": [],
        "interpreter": [
            "/<home-dir>/.pyenv/versions/3.10.5/envs/<project>/bin/python"
        ],
        "importStrategy": "useBundled",
        "showNotifications": "off"
    }
]

Global settings:
{
    "check": false,
    "cwd": "/",
    "workspace": "/",
    "logLevel": "error",
    "args": [
        "--profile",
        "black"
    ],
    "severity": {
        "W": "Warning",
        "E": "Hint"
    },
    "path": [],
    "interpreter": [], "importStrategy": "useBundled", "showNotifications": "off"
}

/<home-dir>/.pyenv/versions/3.10.5/envs/<project>/bin/python -m isort --version-number
CWD Linter: <path-to-project-workspace>
Version info for isort running for <path-to-project-workspace>:
5.11.5

SUPPORTED isort>=5.10.1
FOUND isort==5.11.5

/<home-dir>/.pyenv/versions/3.10.5/envs/<project>/bin/python -m isort - --profile black --filename /Users/<user>/Library/Application Support/Code/User/globalStorage/buenon.scratchpads/scratchpads/1a4f2b73c916c9af3926773a674c6453/scratch2.py
CWD Linter: /<home-dir>/Library/Application Support/Code/User/globalStorage/buenon.scratchpads/scratchpads/1a4f2b73c916c9af3926773a674c6453
```

**Comment by karthiknadig** [comment]
@geoff-va Here is what I am seeing, running `isort` and `black`, without VS code involved:
```console
>type isort_test.py
from urllib import (parse, request)

>type isort_test.py | isort - --profile black --filename isort_test.py
from urllib import parse, request

>type isort_test.py | isort - --profile black --filename isort_test.py | black --stdin-filename isort_test.py -
from urllib import parse, request
All done! ✨ 🍰 ✨
1 file left unchanged.
```

As you can see the code was formatted to:
```python
from urllib import parse, request
```

This is the same result I get with VS Code:
![image](https://user-images.githubusercontent.com/3840081/231048791-dabea281-ce2b-45a6-a195-290c7d16006f.png)

**Comment by karthiknadig** [comment]
Also, running purely via command line without `stdin` also gives the same result:

```console
>type isort_test.py
from urllib import (parse, request)

>isort --profile black isort_test.py
Fixing C:\GIT\differ\isort_test.py

>type isort_test.py
from urllib import parse, request

>black isort_test.py
All done! ✨ 🍰 ✨
1 file left unchanged.

>type isort_test.py
from urllib import parse, request

```

So, I think the result that you are seeing is correct. If not then this is a bug in `isort` itself.

**Comment by geoff-va** [comment]
Thanks @karthiknadig 

With the trailing comma do you still get the same result?

Based on the options I'm seeing here for the [black profile](https://pycqa.github.io/isort/docs/configuration/profiles.html) with the [split_on_trailing_comma](https://pycqa.github.io/isort/docs/configuration/options.html#split-on-trailing-comma) option and [multi_line_output=3](https://pycqa.github.io/isort/docs/configuration/multi_line_output_modes.html) I would think that this:

```python
from urllib import (parse, request, )
```

Would get turned into:

```python
from urllib import (
    parse, 
    request
)

? Unless I'm misunderstanding how this works?

**Comment by geoff-va** [comment]
Ah - It seems to be a [mismatch between docs and implementation](https://github.com/PyCQA/isort/issues/2091) in isort.

When i add the `--split-on-trailing-comma` option it indeed sorts as I would expect based on the black profile. So looks like that option needs to be fixed on the isort side.

Thanks for checking for me, though!
