### ISSUE TITLE
`--profile black` doesn't work with bundled `isort`

### ISSUE THREAD

**Issue by GarrisonD** [microsoft/vscode-isort#269]
In `Output` I can see:

```
/usr/local/bin/python3 -m isort - --profile black --filename /some-dir/some-file.py
```

If I copy this line and just paste in the terminal I get:

```
/usr/local/opt/python@3.11/bin/python3.11: No module named isort
```

But somehow imports get reformatted (just alphabetically but anyway) in VS Code... That's 🪄

**Comment by karthiknadig** [comment]
@GarrisonD The bundled `isort` is not in your environment, so you cannot run the command line as is, if you want this to work from command line then do this:
1. install `isort` in your environment
2. Set `isort.importStrategy` to `fromEnvironment`

The way we use the bundled `isort` is by adding it to path when running the server. This is done avoid isort or its dependencies interfering with your environment.

**Comment by GarrisonD** [comment]
Make sense. But why doesn't `--profile black` work with bundled `isort`? Isn't it just a set of configurations being applied?

**Comment by karthiknadig** [comment]
Share your full settings and logs, it should work:
![image](https://user-images.githubusercontent.com/3840081/233724639-5b0ce7e9-6740-4080-9b4c-d692e22495c5.png)

This is how I have it in my settings:
```
    "isort.args": ["--profile", "black"],
```

**Comment by karthiknadig** [comment]
if you set `    "isort.logLevel": "debug",` it should give you detailed info on where it is picking up each setting.

**Comment by GarrisonD** [comment]
In `Output` I see that this option is passed but the result is different to isort that I run in a Docker container. The only difference I can think about is that on the host I don't have any libs and in the Docker container I have:

- When I sort in VS Code with host's Python then all the imports are sorted alphabetically without any breaks.
- When I sort in the Docker container isort somehow understands the difference between my imports and libs and adds an empty line between two blocks of imports.

**Comment by karthiknadig** [comment]
Set ` "isort.logLevel": "debug"` and see the logs, `isort` looks for settings from several locations including your home directory. I recommend comparing the settings it finds between the two environments.

When I say settings i don't mean isort extension setting. with debug mode set the extension will run `isort --show-config`, I recommend getting log and check between the two environments and seeing why it differs.

**Comment by GarrisonD** [comment]
@karthiknadig  With your advice, I could fix investigate and solve all the issues. Thanks a lot!
