### ISSUE TITLE
When I execute a shortcut command, two sortimports appear. How to set them to the default one

### ISSUE THREAD

**Issue by ugvibib** [microsoft/vscode-isort#273]
When I execute a shortcut command "shift+alt+o", two sortimports appear. 
![2023-04-28 141303](https://user-images.githubusercontent.com/23163237/235069040-73244677-f3d6-4725-a2e0-1ad4a720770f.png)

How to proceed directly without having to choose??

extra info:
python=3.11.2
django=4.2
sort interpreter python=3.8
vscode=1.77.3
isort=v2023.9.11141005

![2023-04-28 141735](https://user-images.githubusercontent.com/23163237/235069645-9deac0c2-45e1-4f2d-8f44-bf0f09073278.png)

![image](https://user-images.githubusercontent.com/23163237/235069852-7bee2dbc-c1bb-4b13-8495-1ce5721461ab.png)

**Comment by ugvibib** [comment]
> @ugvibib This can happen if you have more than one import organizer installed. Do you by chance have `ruff` extension installed?

The following are the plugins I installed. Is it because the Python plugin has not been upgraded?? I didn't try~
![屏幕截图 2023-05-04 132025](https://user-images.githubusercontent.com/23163237/236118583-c0478c47-81d0-4a5f-83b4-db291aef9b08.png)

**Comment by ugvibib** [comment]
> @karthiknadig  This can happen if you have more than one import organizer installed. Do you by chance have `ruff` extension installed?
I haven't installed too many plugins, is it because Python plugins haven't been upgraded? I didn't try to upgrade~
![屏幕截图 2023-05-04 132025](https://user-images.githubusercontent.com/23163237/236118922-be64eabb-85cc-4270-b4d4-3bc548a2c81c.png)

**Comment by ugvibib** [comment]
> @karthiknadig  This can happen if you have more than one import organizer installed. Do you by chance have `ruff` extension installed?

I haven't installed too many plugins, is it because Python plugins haven't been upgraded? I didn't try to upgrade~
![屏幕截图 2023-05-04 132025](https://user-images.githubusercontent.com/23163237/236119253-786ab076-ca1a-4f35-9edd-768f86bf88bd.png)

**Comment by karthiknadig** [comment]
Can you share a screen shot from keyboard bindings? for these two cases?

![image](https://user-images.githubusercontent.com/3840081/236121437-29c764eb-dda9-4f42-8b63-249fd8e7e459.png)

![image](https://user-images.githubusercontent.com/3840081/236121477-a74ec91a-dbb7-4b67-9514-efbafe508767.png)

**Comment by ugvibib** [comment]
@karthiknadig It's similar to yours
![屏幕截图 2023-05-04 180843](https://user-images.githubusercontent.com/23163237/236175387-8645ba3a-4f67-400c-9e41-6b52355b1b4e.png)
![屏幕截图 2023-05-04 180919](https://user-images.githubusercontent.com/23163237/236175410-6501e4d2-52a2-4c61-8253-b20ade659275.png)
