### ISSUE TITLE
Can the need to run isort be shown in the "Problems" area of VS Code?

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/vscode-isort#274]
I see in my python file that imports that are not sorted are indicated with a small squiggle under the first import.

It would be nice if the error was also shown in the "Problems" view.  Is that possible?

**Comment by karthiknadig** [comment]
@Dr-Irv You can set this:
```
"isort.severity": {
                        "W": "Warning",
                        "E": "Error"
                    },
```

The default severity level is `Hint` for isort issues, so it is not shown in the problems view.
