### ISSUE TITLE
isort extension: `Client could not create server to connection. Missing module jsonrpc.`

### ISSUE THREAD

**Issue by DakshKK** [microsoft/vscode-isort#280]
When trying to run isort, it gives an error that the server failed to start 5 times in 3 times, and then informs me that it failed to start.

I'm starting VSCode from within my WSL environment with Python 3.11, inside a virtualenv enabled by `pipenv shell`.

I'm on Ubuntu 23.04.

From what I could derive from the logs, it's giving an error about missing module `jsonrpc`. Some other python extensions, namely `flake8` print missing module `lsp_jsonrpc`.

**Comment by karthiknadig** [comment]
@DakshKK Can you share the full logs please?

**Comment by karthiknadig** [comment]
Because we have not heard back with the information we requested, we are closing this issue for now. If you are able to provide the info later on then we will be happy to re-open this issue to pick up where we left off.
