### ISSUE TITLE
no command in command palette when using notebooks

### ISSUE THREAD

**Issue by TTTPOB** [microsoft/vscode-isort#281]
opened a jupyter notebook in python language in vscode, want to sort import, but there is no such command in command palette
![image](https://github.com/microsoft/vscode-isort/assets/19909103/44b5492c-16a3-487b-9f9b-6cf487360bb8)

I can confirm this work flawlessly in normal python file

vscode version: 1.79.0-insider (user setup)
isort extension version: v2022.8.0

**Comment by karthiknadig** [comment]
This currently is not supported in notebooks. Waiting on this to be implemented in an underlying library: https://github.com/openlawlibrary/pygls/issues/311

**Comment by torext** [comment]
> This currently is not supported in notebooks. Waiting on this to be implemented in an underlying library: [openlawlibrary/pygls#311](https://github.com/openlawlibrary/pygls/issues/311)

Actually this used to work fine in `v2022.8.0`, it's only as of `2023.10.0` that this doesn't work anymore! So this is a bug and not a feature request...

**Comment by karthiknadig** [comment]
There are two parts to this bug:
1. The Cell import sorting stopped showing up is a regression.
2. The full notebook support is still the one I mentioned in my comment above.

@torext thanks for reporting the issue. the fix should be in pre-release.

**Comment by torext** [comment]
Thanks, will install pre-release!

**Comment by TTTPOB** [comment]
> The Cell import sorting stopped showing up is a regression.

![image](https://github.com/microsoft/vscode-isort/assets/19909103/c04f7087-9406-45b0-80e5-2ab68cc54d97)
I've installed pre-release version `v2023.11.12711013`, but I can't find the sort import command in command palette.

**Comment by karthiknadig** [comment]
@TTTPOB The command is `Organize Imports`
<img width="654" alt="image" src="https://github.com/microsoft/vscode-isort/assets/3840081/a4f8b6f5-1b2c-4d4c-9b6c-5d61479cab1d">

Previously, python extension contributed a custom command `Sort Imports`. This did not integrate with VS Code's internal mechanism to fix import organization issues. The `isort` extension integrates with the `Organize Import` feature.

**Comment by TTTPOB** [comment]
> @TTTPOB The command is Organize Imports

Thank you! I didn't know that.
