### ISSUE TITLE
`typeguard` incompatibility: "The isort server crashed 5 times in the last 3 minutes. The server will not be restarted."

### ISSUE THREAD

**Issue by pahwaranger** [microsoft/vscode-isort#282]
isort server crashes if `typeguard` is installed in the same python environment. verified with `typeguard==3.0.2` and `typeguard==4.0.0` (latest).

steps to reproduce:
```
> mkdir isort_test
> cd isort_test 
> virtualenv .venv
created virtual environment CPython3.8.8.final.0-64 in 472ms
  creator CPython3Posix(dest=/Users/amit.pahwa/repos/isort_test/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/amit.pahwa/Library/Application Support/virtualenv)
    added seed packages: pip==22.0.4, setuptools==62.1.0, wheel==0.40.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
> source .venv/bin/activate
(.venv) > pip install isort
Collecting isort
  Using cached isort-5.12.0-py3-none-any.whl (91 kB)
Installing collected packages: isort
Successfully installed isort-5.12.0
```

Open `isort_test` in vscode and create a `test.py` file to trigger isort server to start. Verify that it runs without issue (check `Output` > `isort`). Try both `bundled` and `fromEnvironment`.
![image](https://github.com/microsoft/vscode-isort/assets/12738874/bcb3aa35-1990-4590-a7d1-61f1fd0ef0e9)

Install typeguard:
```
(.venv) > pip install typeguard==4.0.0
(.venv) > pip freeze
importlib-metadata==6.6.0
isort==5.12.0
typeguard==4.0.0
typing_extensions==4.5.0
zipp==3.15.0

```

Re-test isort by toggling between `bundled` and `fromEnvironment`. When in `fromEnvironment` mode, it will show the following error:
```
Traceback (most recent call last):
  File "/Users/amit.pahwa/.vscode/extensions/ms-python.isort-2022.8.0/bundled/tool/server.py", line 195, in <module>
    def code_action_organize_imports(params: lsp.CodeActionParams):
  File "/Users/amit.pahwa/.vscode/extensions/ms-python.isort-2022.8.0/bundled/libs/pygls/feature_manager.py", line 176, in decorator
    raise TypeError(
TypeError: Options of method "textDocument/codeAction" should be instance of type typing.Union[pygls.lsp.types.language_features.code_action.CodeActionOptions, pygls.lsp.types.language_features.code_action.CodeActionRegistrationOptions]
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 9:54:30 PM] Connection to server got closed. Server will restart.
...
[Error - 9:54:32 PM] Connection to server got closed. Server will not be restarted.
```

Running `isort` manually from terminal results in no issue.

Verified the issue does not exist when only the dependencies are installed (`typing_extensions`, `importlib-metadata`, `zipp`), so the conflict must be with `typeguard` code itself.

**Comment by karthiknadig** [comment]
You can also try the server less mode (should be available in pre-release).

This should be addressed in `pygls`. When it is addressed there, I will push a new pre-release.

**Comment by pahwaranger** [comment]
@karthiknadig thanks, ill give serverless mode a shot. is there a ticket in `pygls` I can refer to?

**Comment by karthiknadig** [comment]
There are two options here:
1. `pygls` uses typeguard 3.* so you can set the `importStragtegy` to `useBundled` and it should use the bundled typeguard which will be `3.*`. **This is currently in the pre-release version of the isort extension 2023.9**.
https://github.com/microsoft/vscode-isort/blob/41b6381eb797e178caef97ae42882490526b0645/requirements.txt#L43
2. OR, you can use the serverless mode.

**Comment by karthiknadig** [comment]
> is there a ticket in pygls I can refer to?

No. Try the pre-release version, if that does not work for you then we may have to create a ticket on pygls.

**Comment by pahwaranger** [comment]
the error still shows up with `typeguard==3.0.2` in local environment following the steps in the issue description.

switching to the pre-release _did_ fix the issue though

**Comment by karthiknadig** [comment]
A new stable is released. Please let us know if this does not work.
