### ISSUE TITLE
Can both isort and black run on save?

### ISSUE THREAD

**Issue by jack89roberts** [microsoft/vscode-isort#29]
Thanks for your work on this! Using the config from the readme (copied below for reference) I need to save the file I'm working on twice. The first time `isort` fixes import order, and the second time `black` runs. Is it possible to get them both to run in one go?

```
  "[python]": {
    "editor.defaultFormatter": "ms-python.black-formatter",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    },
    "isort.args":["--profile", "black"]
  }
```

**Comment by karthiknadig** [comment]
@jack89roberts Just to confirm are you using the `ms-python.black-formatter` extension? or are you using `ms-python.python` extension for formatting?

**Comment by jack89roberts** [comment]
With `ms-pytthon.black-formatter`, my full `setings.json`  (User, no additional Workspace settings) is:

```json
{
    "workbench.colorTheme": "Default Dark+",
    "python.condaPath": "conda",
    "python.linting.flake8Enabled": true,
    "python.linting.mypyEnabled": true,
    "python.testing.pytestEnabled": true,
    "editor.rulers": [88],
    "python.linting.pylintEnabled": true,
    "files.autoSave": "afterDelay",
    "autoDocstring.docstringFormat": "numpy",
    "[python]": {
        "editor.defaultFormatter": "ms-python.black-formatter",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        },
    },
    "workbench.iconTheme": "vscode-icons",
    "terminal.integrated.fontFamily": "MesloLGS NF",
    "terminal.integrated.inheritEnv": false,
}
```

On VS Code Version: 1.66.2 (Universal), Mac OS 12.3.1

If I start with:
```python
import pathtlib
import os
var = 'hi'
def hello():
    print('hello')
```

After first save it's formatted to:
```python
import os

import pathtlib

var = 'hi'
def hello():
    print('hello')

```

And after second save:
```python
import os

import pathtlib

var = "hi"


def hello():
    print("hello")

```

**Comment by karthiknadig** [comment]
@jack89roberts I am suspecting, the `"files.autoSave": "afterDelay"` might be interfering with this somehow. Locally, I don't have that set, and it seems to be working as intended, that is, when hit save, `isort` runs first, then `black`, then the file is saved.

Could you also add, `"python.formatting.provider": "none"` that should disable formatting from the python extension, and let black extension handle it. Are you using pre-release version of the python extension? in the pre-release version the python extension detects `isort` extension and avoids running its own `isort`. Eventually we move all tooling to the individual extensions. This inconvenience is only during the transition.

**Comment by jack89roberts** [comment]
Ah right, if I switch to the Python pre-release version both `isort` and `black` happen together, thanks! 👍  

And yes the formatting doesn't work with the autosave, I have to manually save the file for the autoformat to trigger.
