### ISSUE TITLE
Unexpected error in LSP server when saving file if `source.organizeImports` is false

### ISSUE THREAD

**Issue by shayded-exe** [microsoft/vscode-isort#302]
The extension completely breaks if organizeImports is set to false. I want to disable import sorting in just some contexts.

**Comment by karthiknadig** [comment]
@shayded-exe Please provide the version details. Also, you can disable the extension per workspace if you don't want to use it. Please also share logs from Output > isort.

**Comment by shayded-exe** [comment]
I'm using version `2022.8.0`.

I understand I can just disable the extension (which I've done), but this means that I can't have a multi-root workspace where some use it and others don't (I don't want to use it on editable third party libs).
Regardless, I would expect the extension to respect the `organizeImports` setting.

The log doesn't print anything when the error happens. I checked all the extension logs including pylance.

**Comment by shayded-exe** [comment]
Additionally, I would like to be able to have automatic sorting disabled, but still explicitly sort via command if I want.

**Comment by karthiknadig** [comment]
Can you try the pre-release version? This was fixed when we updated handling of the Language Server Protocol.

If you continue to see the issue with pre-release version, add this to your settings and reload and repro the problem and share the logs from Output > isort

```
"isort.trace.server": "verbose"
```

**Comment by karthiknadig** [comment]
I tested this with pre-release version `2023.9.`
![image](https://github.com/microsoft/vscode-isort/assets/3840081/64601416-1fdc-4145-96a4-361c4bfd4fa6)

This should be fixed.

**Comment by shayded-exe** [comment]
The latest version is working. Thank you!
