### ISSUE TITLE
Using isort with Jupyter Notebooks

### ISSUE THREAD

**Issue by jvhoffbauer** [microsoft/vscode-isort#315]
Is it possible to use isort with Jupyter Notebooks in VSCode?

**Comment by karthiknadig** [comment]
You should be able to trigger sort import for Notebooks.

@Yoyokrazy This is the current selection criteria in the doc selector:
https://github.com/microsoft/vscode-isort/blob/fe9b8985c0c09bf5952b4ed5de68c30c74aed365/src/common/utilities.ts#L75-L78

This should be enough as far as I understand.

**Comment by alexdauenhauer** [comment]
@karthiknadig are you saying it should already work out of the box? maybe I misunderstood your comment. It definitely does not currently run on jupyter notebooks for me

**Comment by karthiknadig** [comment]
@alexdauenhauer You should be able to see what was triggered in the Output > isort logs

**Comment by karthiknadig** [comment]
The command you need to call is `Organize Imports`

**Comment by bilzard** [comment]
I set both `isort.args` and `organizeImports` setting on `settings.json`, however, imports are not sorted on save.
Am I missing something?

```python
    "[python]": {
        "editor.defaultFormatter": "ms-python.black-formatter",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        },
        "editor.formatOnType": true
    },
    "isort.args": [
        "--profile",
        "black"
    ],
```

**Comment by bilzard** [comment]
May my problem is related to this issue.
https://github.com/microsoft/vscode-isort/issues/303

**Comment by jtele2** [comment]
Can this be done on save? I can't seem to get it to work on save.

**Comment by realguoqiang** [comment]
@nonoash 

Try using 
```json
"notebook.codeActionsOnSave": {
    "source.organizeImports": "explicit"
  },
"isort.args": [
  "--profile",
  "black"
],
```
