### ISSUE TITLE
Improve setting description for default interpreter setting

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-isort#325]
Same issue as this: https://github.com/microsoft/vscode-mypy/issues/144

Improve description of the default value of the setting. When it's set to `[]` it will use the Python extension's selected interpreter. If it's set to a path, it will use that value as the interpreter. See this PR: https://github.com/microsoft/vscode-mypy/pull/152/files

**Comment by luabud** [comment]
We are reserving this issue for Grace Hopper's Open Source Day, which will take place on September 22nd, 2023. If you're part of the event and would like to submit a contribution to this issue, please let us know, and we'll be happy to assign it to you.

For other community members who are not participating in the event, we appreciate your interest in contributing! We kindly request that you wait until after September 22nd to work on this issue. If no one from the event has been assigned to it by then, we'll gladly assign it to you. Thank you for your understanding and support!

**Comment by Riddhi-Thanki** [comment]
Hi, I am participating in GHC. Can you assign this issue to me?

**Comment by hyndavi17** [comment]
Can I please be assigned @eleanorjboyd

**Comment by eleanorjboyd** [comment]
Hi @hyndavi17 this has already been assigned to @Riddhi-Thanki so you could find another issue to work on or ask to collaborate to do a join PR with @Riddhi-Thanki. Thanks!

**Comment by hyndavi17** [comment]
> Hi, I am participating in GHC. Can you assign this issue to me?

Can we do a joint PR? if its okay with you @Riddhi-Thanki

**Comment by Riddhi-Thanki** [comment]
Hey @hyndavi17, I have already created a merge request for this issue!

**Comment by luabud** [comment]
https://github.com/microsoft/vscode-isort/pull/328
