### ISSUE TITLE
Add Python 3.12-dev to tests actions 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-isort#326]
We should add Python 3.12-dev here and see if all tests pass: https://github.com/microsoft/vscode-isort/blob/main/.github/workflows/pr-check.yml

**Comment by pheonix-18** [comment]
Can I take this issue @luabud

**Comment by eleanorjboyd** [comment]
@karthiknadig, this addition failed on the python repo- do we anticipate it will work on this repo?

**Comment by pheonix-18** [comment]
#330
