### ISSUE TITLE
bug: lines being deleted when setting organizeImports to explicit

### ISSUE THREAD

**Issue by alexdashly** [microsoft/vscode-isort#391]
Hi,

I have a very basic python file I was able to replicate this on.  Here it is in its base state:

```python
from abc import abstractmethod

from pydantic import BaseModel

test = "abc"


def func() -> None:
    return None
```

Here is my `settings.json` file:
```json
{
  "editor.formatOnSaveMode": "file",
  "editor.formatOnSave": true,
  "git.decorations.enabled": false,
  "[python]": {
    "editor.defaultFormatter": "ms-python.black-formatter",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.organizeImports": "explicit"
    }
  },
  "isort.args": ["--profile", "black"],
  "editor.rulers": [88],
  "files.exclude": {
    "**/.venv": true,
    "**/reports": true
  }
}
```

If I add lines above `test = ...` (in an unsaved state looks like this)
```
from abc import abstractmethod

from pydantic import BaseModel





test = "abc"


def func() -> None:
    return None
```
then when I save and everything runs, lines end up getting deleted
```python
from abc import abstractmethod

from pydantic import BaseModel

    return None
```

I can fix this behavior by commenting out `"source.organizeImports": "explicit"`.

I appear to be on the latest version of the extension but I don't know where to go to show the specific version info.

**Comment by karthiknadig** [comment]
@alexdashly Do you have any other import organizer installed like `ruff` ? This happens if you have more than one installed. In that case you have to be more explicit in your settings like `"source.organizeImports.isort": "explicit"` (to use isort) or `"source.organizeImports.ruff": "explicit"` (to use ruff)

**Comment by alexdashly** [comment]
Ah, that would do it!  Makes total sense.  All fixed now.  Thanks.
